export const sportActionTypes = {
  GET_FOOTBALL_REQUEST: 'GET_FOOTBALL_REQUEST',
  GET_BASKETBALL_REQUEST: 'GET_BASKETBALL_REQUEST',
  GET_RUGBY_REQUEST: 'GET_RUGBY_REQUEST',
  GET_VALLEYBALL_REQUEST: 'GET_VALLEYBALL_REQUEST',
  SPORT_REQUEST_SUCCEED: 'SPORT_REQUEST_SUCCEED',
};

export const SET_LOADING_STATE = 'SET_LOADING_STATE';
export const ERROR_STATE = 'ERROR_STATE';
export const SET_SPORT_TYPE = 'SET_SPORT_TYPE';
