export const sportActionTypes = {
    GET_FOOTBALL_REQUEST: 'GET_FOOTBALL_REQUEST',
    FOOTBALL_REQUEST_SUCCEED: 'FOOTBALL_REQUEST_SUCCEED',
    GET_BASKETBALL_REQUEST: 'GET_BASKETBALL_REQUEST',
    BASKETBALL_REQUEST_SUCCEED: 'BASKETBALL_REQUEST_SUCCEED',
    GET_RUGBY_REQUEST: 'GET_RUGBY_REQUEST',
    RUGBY_REQUEST_SUCCEED: 'RUGBY_REQUEST_SUCCEED',
    GET_VALLEYBALL_REQUEST: 'GET_VALLEYBALL_REQUEST',
    VALLEYBALL_REQUEST_SUCCEED: 'VALLEYBALL_REQUEST_SUCCEED',

};

export const SET_LOADING_STATE = 'SET_LOADING_STATE';
export const ERROR_STATE = 'ERROR_STATE';
export const SET_SPORT_TYPE = 'SET_SPORT_TYPE';

