export default [
  {
    match_id: '182550',
    country_id: '68',
    country_name: 'Italy',
    league_id: '268',
    league_name: 'Serie D - Group A',
    match_date: '2019-03-03',
    match_status: 'Finished',
    match_time: '14:30',
    match_hometeam_id: '4346',
    match_hometeam_name: 'Tuttocuoio',
    match_hometeam_score: '0',
    match_awayteam_name: 'San Donato',
    match_awayteam_id: '12413',
    match_awayteam_score: '1',
    match_hometeam_halftime_score: '',
    match_awayteam_halftime_score: '',
    match_hometeam_extra_score: '',
    match_awayteam_extra_score: '',
    match_hometeam_penalty_score: '',
    match_awayteam_penalty_score: '',
    match_hometeam_system: '',
    match_awayteam_system: '',
    match_live: '0',
    goalscorer: [],
    cards: [],
    substitutions: {
      home: [],
      away: [],
    },
    lineup: {
      home: {
        starting_lineups: [],
        substitutes: [],
        coach: [],
        missing_players: [],
      },
      away: {
        starting_lineups: [],
        substitutes: [],
        coach: [],
        missing_players: [],
      },
    },
    statistics: [],
  },
  {
    match_id: '182551',
    country_id: '68',
    country_name: 'Italy',
    league_id: '268',
    league_name: 'Serie D - Group A',
    match_date: '2019-03-03',
    match_status: 'Finished',
    match_time: '14:30',
    match_hometeam_id: '13182',
    match_hometeam_name: 'UC Sinalunghese',
    match_hometeam_score: '1',
    match_awayteam_name: 'Cannara',
    match_awayteam_id: '13176',
    match_awayteam_score: '1',
    match_hometeam_halftime_score: '',
    match_awayteam_halftime_score: '',
    match_hometeam_extra_score: '',
    match_awayteam_extra_score: '',
    match_hometeam_penalty_score: '',
    match_awayteam_penalty_score: '',
    match_hometeam_system: '',
    match_awayteam_system: '',
    match_live: '0',
    goalscorer: [],
    cards: [],
    substitutions: {
      home: [],
      away: [],
    },
    lineup: {
      home: {
        starting_lineups: [],
        substitutes: [],
        coach: [],
        missing_players: [],
      },
      away: {
        starting_lineups: [],
        substitutes: [],
        coach: [],
        missing_players: [],
      },
    },
    statistics: [],
  },
  {
    match_id: '182552',
    country_id: '68',
    country_name: 'Italy',
    league_id: '268',
    league_name: 'Serie D - Group A',
    match_date: '2019-03-03',
    match_status: 'Finished',
    match_time: '14:30',
    match_hometeam_id: '13184',
    match_hometeam_name: 'Viareggio',
    match_hometeam_score: '0',
    match_awayteam_name: 'Trestina',
    match_awayteam_id: '4345',
    match_awayteam_score: '1',
    match_hometeam_halftime_score: '',
    match_awayteam_halftime_score: '',
    match_hometeam_extra_score: '',
    match_awayteam_extra_score: '',
    match_hometeam_penalty_score: '',
    match_awayteam_penalty_score: '',
    match_hometeam_system: '',
    match_awayteam_system: '',
    match_live: '0',
    goalscorer: [],
    cards: [],
    substitutions: {
      home: [],
      away: [],
    },
    lineup: {
      home: {
        starting_lineups: [],
        substitutes: [],
        coach: [],
        missing_players: [],
      },
      away: {
        starting_lineups: [],
        substitutes: [],
        coach: [],
        missing_players: [],
      },
    },
    statistics: [],
  },
  {
    match_id: '182553',
    country_id: '68',
    country_name: 'Italy',
    league_id: '268',
    league_name: 'Serie D - Group A',
    match_date: '2019-03-03',
    match_status: 'Finished',
    match_time: '14:30',
    match_hometeam_id: '13185',
    match_hometeam_name: 'Agnonese',
    match_hometeam_score: '0',
    match_awayteam_name: 'Recanatese',
    match_awayteam_id: '13192',
    match_awayteam_score: '3',
    match_hometeam_halftime_score: '',
    match_awayteam_halftime_score: '',
    match_hometeam_extra_score: '',
    match_awayteam_extra_score: '',
    match_hometeam_penalty_score: '',
    match_awayteam_penalty_score: '',
    match_hometeam_system: '',
    match_awayteam_system: '',
    match_live: '0',
    goalscorer: [],
    cards: [],
    substitutions: {
      home: [],
      away: [],
    },
    lineup: {
      home: {
        starting_lineups: [],
        substitutes: [],
        coach: [],
        missing_players: [],
      },
      away: {
        starting_lineups: [],
        substitutes: [],
        coach: [],
        missing_players: [],
      },
    },
    statistics: [],
  },
  {
    match_id: '182554',
    country_id: '68',
    country_name: 'Italy',
    league_id: '268',
    league_name: 'Serie D - Group A',
    match_date: '2019-03-03',
    match_status: 'Finished',
    match_time: '14:30',
    match_hometeam_id: '9130',
    match_hometeam_name: 'Avezzano',
    match_hometeam_score: '2',
    match_awayteam_name: 'Santarcangelo',
    match_awayteam_id: '4247',
    match_awayteam_score: '0',
    match_hometeam_halftime_score: '',
    match_awayteam_halftime_score: '',
    match_hometeam_extra_score: '',
    match_awayteam_extra_score: '',
    match_hometeam_penalty_score: '',
    match_awayteam_penalty_score: '',
    match_hometeam_system: '',
    match_awayteam_system: '',
    match_live: '0',
    goalscorer: [],
    cards: [],
    substitutions: {
      home: [],
      away: [],
    },
    lineup: {
      home: {
        starting_lineups: [],
        substitutes: [],
        coach: [],
        missing_players: [],
      },
      away: {
        starting_lineups: [],
        substitutes: [],
        coach: [],
        missing_players: [],
      },
    },
    statistics: [],
  },
  {
    match_id: '182555',
    country_id: '68',
    country_name: 'Italy',
    league_id: '268',
    league_name: 'Serie D - Group A',
    match_date: '2019-03-03',
    match_status: 'Finished',
    match_time: '14:30',
    match_hometeam_id: '13188',
    match_hometeam_name: 'Castelfidardo',
    match_hometeam_score: '0',
    match_awayteam_name: 'Jesina',
    match_awayteam_id: '13193',
    match_awayteam_score: '2',
    match_hometeam_halftime_score: '',
    match_awayteam_halftime_score: '',
    match_hometeam_extra_score: '',
    match_awayteam_extra_score: '',
    match_hometeam_penalty_score: '',
    match_awayteam_penalty_score: '',
    match_hometeam_system: '',
    match_awayteam_system: '',
    match_live: '0',
    goalscorer: [],
    cards: [],
    substitutions: {
      home: [],
      away: [],
    },
    lineup: {
      home: {
        starting_lineups: [],
        substitutes: [],
        coach: [],
        missing_players: [],
      },
      away: {
        starting_lineups: [],
        substitutes: [],
        coach: [],
        missing_players: [],
      },
    },
    statistics: [],
  },
  {
    match_id: '182556',
    country_id: '68',
    country_name: 'Italy',
    league_id: '268',
    league_name: 'Serie D - Group A',
    match_date: '2019-03-03',
    match_status: 'Finished',
    match_time: '14:30',
    match_hometeam_id: '4196',
    match_hometeam_name: 'Cesena',
    match_hometeam_score: '3',
    match_awayteam_name: 'Isernia',
    match_awayteam_id: '13190',
    match_awayteam_score: '1',
    match_hometeam_halftime_score: '',
    match_awayteam_halftime_score: '',
    match_hometeam_extra_score: '',
    match_awayteam_extra_score: '',
    match_hometeam_penalty_score: '',
    match_awayteam_penalty_score: '',
    match_hometeam_system: '',
    match_awayteam_system: '',
    match_live: '0',
    goalscorer: [],
    cards: [],
    substitutions: {
      home: [],
      away: [],
    },
    lineup: {
      home: {
        starting_lineups: [],
        substitutes: [],
        coach: [],
        missing_players: [],
      },
      away: {
        starting_lineups: [],
        substitutes: [],
        coach: [],
        missing_players: [],
      },
    },
    statistics: [],
  },
  {
    match_id: '182557',
    country_id: '68',
    country_name: 'Italy',
    league_id: '268',
    league_name: 'Serie D - Group A',
    match_date: '2019-03-03',
    match_status: 'Finished',
    match_time: '14:30',
    match_hometeam_id: '13186',
    match_hometeam_name: 'Giulianova',
    match_hometeam_score: '2',
    match_awayteam_name: 'Savignanese',
    match_awayteam_id: '13197',
    match_awayteam_score: '1',
    match_hometeam_halftime_score: '',
    match_awayteam_halftime_score: '',
    match_hometeam_extra_score: '',
    match_awayteam_extra_score: '',
    match_hometeam_penalty_score: '',
    match_awayteam_penalty_score: '',
    match_hometeam_system: '',
    match_awayteam_system: '',
    match_live: '0',
    goalscorer: [],
    cards: [],
    substitutions: {
      home: [],
      away: [],
    },
    lineup: {
      home: {
        starting_lineups: [],
        substitutes: [],
        coach: [],
        missing_players: [],
      },
      away: {
        starting_lineups: [],
        substitutes: [],
        coach: [],
        missing_players: [],
      },
    },
    statistics: [],
  },
  {
    match_id: '182558',
    country_id: '68',
    country_name: 'Italy',
    league_id: '268',
    league_name: 'Serie D - Group A',
    match_date: '2019-03-03',
    match_status: 'Finished',
    match_time: '14:30',
    match_hometeam_id: '11640',
    match_hometeam_name: 'Matelica',
    match_hometeam_score: '2',
    match_awayteam_name: 'Sangiustese',
    match_awayteam_id: '13195',
    match_awayteam_score: '0',
    match_hometeam_halftime_score: '',
    match_awayteam_halftime_score: '',
    match_hometeam_extra_score: '',
    match_awayteam_extra_score: '',
    match_hometeam_penalty_score: '',
    match_awayteam_penalty_score: '',
    match_hometeam_system: '',
    match_awayteam_system: '',
    match_live: '0',
    goalscorer: [],
    cards: [],
    substitutions: {
      home: [],
      away: [],
    },
    lineup: {
      home: {
        starting_lineups: [],
        substitutes: [],
        coach: [],
        missing_players: [],
      },
      away: {
        starting_lineups: [],
        substitutes: [],
        coach: [],
        missing_players: [],
      },
    },
    statistics: [],
  },
  {
    match_id: '182559',
    country_id: '68',
    country_name: 'Italy',
    league_id: '268',
    league_name: 'Serie D - Group A',
    match_date: '2019-03-03',
    match_status: 'Finished',
    match_time: '14:30',
    match_hometeam_id: '13194',
    match_hometeam_name: 'Montegiorgio',
    match_hometeam_score: '3',
    match_awayteam_name: 'Campobasso',
    match_awayteam_id: '13196',
    match_awayteam_score: '2',
    match_hometeam_halftime_score: '',
    match_awayteam_halftime_score: '',
    match_hometeam_extra_score: '',
    match_awayteam_extra_score: '',
    match_hometeam_penalty_score: '',
    match_awayteam_penalty_score: '',
    match_hometeam_system: '',
    match_awayteam_system: '',
    match_live: '0',
    goalscorer: [],
    cards: [],
    substitutions: {
      home: [],
      away: [],
    },
    lineup: {
      home: {
        starting_lineups: [],
        substitutes: [],
        coach: [],
        missing_players: [],
      },
      away: {
        starting_lineups: [],
        substitutes: [],
        coach: [],
        missing_players: [],
      },
    },
    statistics: [],
  },
  {
    match_id: '182560',
    country_id: '68',
    country_name: 'Italy',
    league_id: '268',
    league_name: 'Serie D - Group A',
    match_date: '2019-03-03',
    match_status: 'Finished',
    match_time: '14:30',
    match_hometeam_id: '13189',
    match_hometeam_name: 'S. N. Notaresco',
    match_hometeam_score: '2',
    match_awayteam_name: 'ASD Francavilla',
    match_awayteam_id: '13187',
    match_awayteam_score: '0',
    match_hometeam_halftime_score: '',
    match_awayteam_halftime_score: '',
    match_hometeam_extra_score: '',
    match_awayteam_extra_score: '',
    match_hometeam_penalty_score: '',
    match_awayteam_penalty_score: '',
    match_hometeam_system: '',
    match_awayteam_system: '',
    match_live: '0',
    goalscorer: [],
    cards: [],
    substitutions: {
      home: [],
      away: [],
    },
    lineup: {
      home: {
        starting_lineups: [],
        substitutes: [],
        coach: [],
        missing_players: [],
      },
      away: {
        starting_lineups: [],
        substitutes: [],
        coach: [],
        missing_players: [],
      },
    },
    statistics: [],
  },
  {
    match_id: '182561',
    country_id: '68',
    country_name: 'Italy',
    league_id: '268',
    league_name: 'Serie D - Group A',
    match_date: '2019-03-03',
    match_status: 'Finished',
    match_time: '14:30',
    match_hometeam_id: '4330',
    match_hometeam_name: 'Sammaurese',
    match_hometeam_score: '1',
    match_awayteam_name: 'Forli',
    match_awayteam_id: '4333',
    match_awayteam_score: '1',
    match_hometeam_halftime_score: '',
    match_awayteam_halftime_score: '',
    match_hometeam_extra_score: '',
    match_awayteam_extra_score: '',
    match_hometeam_penalty_score: '',
    match_awayteam_penalty_score: '',
    match_hometeam_system: '',
    match_awayteam_system: '',
    match_live: '0',
    goalscorer: [],
    cards: [],
    substitutions: {
      home: [],
      away: [],
    },
    lineup: {
      home: {
        starting_lineups: [],
        substitutes: [],
        coach: [],
        missing_players: [],
      },
      away: {
        starting_lineups: [],
        substitutes: [],
        coach: [],
        missing_players: [],
      },
    },
    statistics: [],
  },
  {
    match_id: '182562',
    country_id: '68',
    country_name: 'Italy',
    league_id: '268',
    league_name: 'Serie D - Group A',
    match_date: '2019-03-03',
    match_status: 'Finished',
    match_time: '14:30',
    match_hometeam_id: '13191',
    match_hometeam_name: 'Vastese',
    match_hometeam_score: '0',
    match_awayteam_name: 'ASD Pineto Calcio',
    match_awayteam_id: '9150',
    match_awayteam_score: '1',
    match_hometeam_halftime_score: '',
    match_awayteam_halftime_score: '',
    match_hometeam_extra_score: '',
    match_awayteam_extra_score: '',
    match_hometeam_penalty_score: '',
    match_awayteam_penalty_score: '',
    match_hometeam_system: '',
    match_awayteam_system: '',
    match_live: '0',
    goalscorer: [],
    cards: [],
    substitutions: {
      home: [],
      away: [],
    },
    lineup: {
      home: {
        starting_lineups: [],
        substitutes: [],
        coach: [],
        missing_players: [],
      },
      away: {
        starting_lineups: [],
        substitutes: [],
        coach: [],
        missing_players: [],
      },
    },
    statistics: [],
  },
  {
    match_id: '182563',
    country_id: '68',
    country_name: 'Italy',
    league_id: '268',
    league_name: 'Serie D - Group A',
    match_date: '2019-03-03',
    match_status: 'Finished',
    match_time: '14:30',
    match_hometeam_id: '13213',
    match_hometeam_name: 'Aprilia',
    match_hometeam_score: '1',
    match_awayteam_name: 'Citta di Anagni',
    match_awayteam_id: '13198',
    match_awayteam_score: '0',
    match_hometeam_halftime_score: '',
    match_awayteam_halftime_score: '',
    match_hometeam_extra_score: '',
    match_awayteam_extra_score: '',
    match_hometeam_penalty_score: '',
    match_awayteam_penalty_score: '',
    match_hometeam_system: '',
    match_awayteam_system: '',
    match_live: '0',
    goalscorer: [],
    cards: [],
    substitutions: {
      home: [],
      away: [],
    },
    lineup: {
      home: {
        starting_lineups: [],
        substitutes: [],
        coach: [],
        missing_players: [],
      },
      away: {
        starting_lineups: [],
        substitutes: [],
        coach: [],
        missing_players: [],
      },
    },
    statistics: [],
  },
  {
    match_id: '182564',
    country_id: '68',
    country_name: 'Italy',
    league_id: '268',
    league_name: 'Serie D - Group A',
    match_date: '2019-03-03',
    match_status: 'Finished',
    match_time: '14:30',
    match_hometeam_id: '13201',
    match_hometeam_name: 'Budoni',
    match_hometeam_score: '5',
    match_awayteam_name: 'Latina',
    match_awayteam_id: '11236',
    match_awayteam_score: '2',
    match_hometeam_halftime_score: '',
    match_awayteam_halftime_score: '',
    match_hometeam_extra_score: '',
    match_awayteam_extra_score: '',
    match_hometeam_penalty_score: '',
    match_awayteam_penalty_score: '',
    match_hometeam_system: '',
    match_awayteam_system: '',
    match_live: '0',
    goalscorer: [],
    cards: [],
    substitutions: {
      home: [],
      away: [],
    },
    lineup: {
      home: {
        starting_lineups: [],
        substitutes: [],
        coach: [],
        missing_players: [],
      },
      away: {
        starting_lineups: [],
        substitutes: [],
        coach: [],
        missing_players: [],
      },
    },
    statistics: [],
  },
  {
    match_id: '182565',
    country_id: '68',
    country_name: 'Italy',
    league_id: '268',
    league_name: 'Serie D - Group A',
    match_date: '2019-03-03',
    match_status: 'Finished',
    match_time: '14:30',
    match_hometeam_id: '13200',
    match_hometeam_name: 'Cassino',
    match_hometeam_score: '4',
    match_awayteam_name: 'Flaminia',
    match_awayteam_id: '13205',
    match_awayteam_score: '1',
    match_hometeam_halftime_score: '',
    match_awayteam_halftime_score: '',
    match_hometeam_extra_score: '',
    match_awayteam_extra_score: '',
    match_hometeam_penalty_score: '',
    match_awayteam_penalty_score: '',
    match_hometeam_system: '',
    match_awayteam_system: '',
    match_live: '0',
    goalscorer: [],
    cards: [],
    substitutions: {
      home: [],
      away: [],
    },
    lineup: {
      home: {
        starting_lineups: [],
        substitutes: [],
        coach: [],
        missing_players: [],
      },
      away: {
        starting_lineups: [],
        substitutes: [],
        coach: [],
        missing_players: [],
      },
    },
    statistics: [],
  },
  {
    match_id: '182566',
    country_id: '68',
    country_name: 'Italy',
    league_id: '268',
    league_name: 'Serie D - Group A',
    match_date: '2019-03-03',
    match_status: 'Finished',
    match_time: '14:30',
    match_hometeam_id: '13207',
    match_hometeam_name: 'Castiadas',
    match_hometeam_score: '0',
    match_awayteam_name: 'Avellino',
    match_awayteam_id: '4193',
    match_awayteam_score: '4',
    match_hometeam_halftime_score: '',
    match_awayteam_halftime_score: '',
    match_hometeam_extra_score: '',
    match_awayteam_extra_score: '',
    match_hometeam_penalty_score: '',
    match_awayteam_penalty_score: '',
    match_hometeam_system: '',
    match_awayteam_system: '',
    match_live: '0',
    goalscorer: [],
    cards: [],
    substitutions: {
      home: [],
      away: [],
    },
    lineup: {
      home: {
        starting_lineups: [],
        substitutes: [],
        coach: [],
        missing_players: [],
      },
      away: {
        starting_lineups: [],
        substitutes: [],
        coach: [],
        missing_players: [],
      },
    },
    statistics: [],
  },
  {
    match_id: '182567',
    country_id: '68',
    country_name: 'Italy',
    league_id: '268',
    league_name: 'Serie D - Group A',
    match_date: '2019-03-03',
    match_status: 'Finished',
    match_time: '15:00',
    match_hometeam_id: '13202',
    match_hometeam_name: 'Latte Dolce',
    match_hometeam_score: '1',
    match_awayteam_name: 'Lanusei Calcio',
    match_awayteam_id: '13209',
    match_awayteam_score: '2',
    match_hometeam_halftime_score: '',
    match_awayteam_halftime_score: '',
    match_hometeam_extra_score: '',
    match_awayteam_extra_score: '',
    match_hometeam_penalty_score: '',
    match_awayteam_penalty_score: '',
    match_hometeam_system: '',
    match_awayteam_system: '',
    match_live: '0',
    goalscorer: [],
    cards: [],
    substitutions: {
      home: [],
      away: [],
    },
    lineup: {
      home: {
        starting_lineups: [],
        substitutes: [],
        coach: [],
        missing_players: [],
      },
      away: {
        starting_lineups: [],
        substitutes: [],
        coach: [],
        missing_players: [],
      },
    },
    statistics: [],
  },
  {
    match_id: '182568',
    country_id: '68',
    country_name: 'Italy',
    league_id: '268',
    league_name: 'Serie D - Group A',
    match_date: '2019-03-03',
    match_status: 'Finished',
    match_time: '14:30',
    match_hometeam_id: '13204',
    match_hometeam_name: 'Lupa Roma',
    match_hometeam_score: '4',
    match_awayteam_name: 'Torres',
    match_awayteam_id: '13208',
    match_awayteam_score: '1',
    match_hometeam_halftime_score: '',
    match_awayteam_halftime_score: '',
    match_hometeam_extra_score: '',
    match_awayteam_extra_score: '',
    match_hometeam_penalty_score: '',
    match_awayteam_penalty_score: '',
    match_hometeam_system: '',
    match_awayteam_system: '',
    match_live: '0',
    goalscorer: [],
    cards: [],
    substitutions: {
      home: [],
      away: [],
    },
    lineup: {
      home: {
        starting_lineups: [],
        substitutes: [],
        coach: [],
        missing_players: [],
      },
      away: {
        starting_lineups: [],
        substitutes: [],
        coach: [],
        missing_players: [],
      },
    },
    statistics: [],
  },
  {
    match_id: '182569',
    country_id: '68',
    country_name: 'Italy',
    league_id: '268',
    league_name: 'Serie D - Group A',
    match_date: '2019-03-03',
    match_status: 'Finished',
    match_time: '14:30',
    match_hometeam_id: '13211',
    match_hometeam_name: 'Monterosi FC',
    match_hometeam_score: '3',
    match_awayteam_name: 'SFF Atletico',
    match_awayteam_id: '11736',
    match_awayteam_score: '1',
    match_hometeam_halftime_score: '',
    match_awayteam_halftime_score: '',
    match_hometeam_extra_score: '',
    match_awayteam_extra_score: '',
    match_hometeam_penalty_score: '',
    match_awayteam_penalty_score: '',
    match_hometeam_system: '',
    match_awayteam_system: '',
    match_live: '0',
    goalscorer: [],
    cards: [],
    substitutions: {
      home: [],
      away: [],
    },
    lineup: {
      home: {
        starting_lineups: [],
        substitutes: [],
        coach: [],
        missing_players: [],
      },
      away: {
        starting_lineups: [],
        substitutes: [],
        coach: [],
        missing_players: [],
      },
    },
    statistics: [],
  },
  {
    match_id: '182570',
    country_id: '68',
    country_name: 'Italy',
    league_id: '268',
    league_name: 'Serie D - Group A',
    match_date: '2019-03-03',
    match_status: 'Finished',
    match_time: '14:30',
    match_hometeam_id: '13206',
    match_hometeam_name: 'Ostia Mare',
    match_hometeam_score: '0',
    match_awayteam_name: 'Albalonga',
    match_awayteam_id: '11642',
    match_awayteam_score: '2',
    match_hometeam_halftime_score: '',
    match_awayteam_halftime_score: '',
    match_hometeam_extra_score: '',
    match_awayteam_extra_score: '',
    match_hometeam_penalty_score: '',
    match_awayteam_penalty_score: '',
    match_hometeam_system: '',
    match_awayteam_system: '',
    match_live: '0',
    goalscorer: [],
    cards: [],
    substitutions: {
      home: [],
      away: [],
    },
    lineup: {
      home: {
        starting_lineups: [],
        substitutes: [],
        coach: [],
        missing_players: [],
      },
      away: {
        starting_lineups: [],
        substitutes: [],
        coach: [],
        missing_players: [],
      },
    },
    statistics: [],
  },
  {
    match_id: '182571',
    country_id: '68',
    country_name: 'Italy',
    league_id: '268',
    league_name: 'Serie D - Group A',
    match_date: '2019-03-03',
    match_status: 'Finished',
    match_time: '14:30',
    match_hometeam_id: '13210',
    match_hometeam_name: 'Trastevere Calcio',
    match_hometeam_score: '3',
    match_awayteam_name: 'Ladispoli',
    match_awayteam_id: '13203',
    match_awayteam_score: '1',
    match_hometeam_halftime_score: '',
    match_awayteam_halftime_score: '',
    match_hometeam_extra_score: '',
    match_awayteam_extra_score: '',
    match_hometeam_penalty_score: '',
    match_awayteam_penalty_score: '',
    match_hometeam_system: '',
    match_awayteam_system: '',
    match_live: '0',
    goalscorer: [],
    cards: [],
    substitutions: {
      home: [],
      away: [],
    },
    lineup: {
      home: {
        starting_lineups: [],
        substitutes: [],
        coach: [],
        missing_players: [],
      },
      away: {
        starting_lineups: [],
        substitutes: [],
        coach: [],
        missing_players: [],
      },
    },
    statistics: [],
  },
  {
    match_id: '182572',
    country_id: '68',
    country_name: 'Italy',
    league_id: '268',
    league_name: 'Serie D - Group A',
    match_date: '2019-03-03',
    match_status: 'Finished',
    match_time: '14:30',
    match_hometeam_id: '13212',
    match_hometeam_name: 'Vis Artena',
    match_hometeam_score: '5',
    match_awayteam_name: 'Anzio Calcio 1924',
    match_awayteam_id: '13199',
    match_awayteam_score: '0',
    match_hometeam_halftime_score: '',
    match_awayteam_halftime_score: '',
    match_hometeam_extra_score: '',
    match_awayteam_extra_score: '',
    match_hometeam_penalty_score: '',
    match_awayteam_penalty_score: '',
    match_hometeam_system: '',
    match_awayteam_system: '',
    match_live: '0',
    goalscorer: [],
    cards: [],
    substitutions: {
      home: [],
      away: [],
    },
    lineup: {
      home: {
        starting_lineups: [],
        substitutes: [],
        coach: [],
        missing_players: [],
      },
      away: {
        starting_lineups: [],
        substitutes: [],
        coach: [],
        missing_players: [],
      },
    },
    statistics: [],
  },
  {
    match_id: '182573',
    country_id: '68',
    country_name: 'Italy',
    league_id: '268',
    league_name: 'Serie D - Group A',
    match_date: '2019-03-03',
    match_status: 'Finished',
    match_time: '15:00',
    match_hometeam_id: '12108',
    match_hometeam_name: 'A.C.D. Nardo',
    match_hometeam_score: '1',
    match_awayteam_name: 'Pomigliano',
    match_awayteam_id: '13219',
    match_awayteam_score: '1',
    match_hometeam_halftime_score: '',
    match_awayteam_halftime_score: '',
    match_hometeam_extra_score: '',
    match_awayteam_extra_score: '',
    match_hometeam_penalty_score: '',
    match_awayteam_penalty_score: '',
    match_hometeam_system: '',
    match_awayteam_system: '',
    match_live: '0',
    goalscorer: [],
    cards: [],
    substitutions: {
      home: [],
      away: [],
    },
    lineup: {
      home: {
        starting_lineups: [],
        substitutes: [],
        coach: [],
        missing_players: [],
      },
      away: {
        starting_lineups: [],
        substitutes: [],
        coach: [],
        missing_players: [],
      },
    },
    statistics: [],
  },
  {
    match_id: '182574',
    country_id: '68',
    country_name: 'Italy',
    league_id: '268',
    league_name: 'Serie D - Group A',
    match_date: '2019-03-03',
    match_status: 'Finished',
    match_time: '15:00',
    match_hometeam_id: '13217',
    match_hometeam_name: 'Altamura',
    match_hometeam_score: '2',
    match_awayteam_name: 'Bitonto',
    match_awayteam_id: '13223',
    match_awayteam_score: '1',
    match_hometeam_halftime_score: '',
    match_awayteam_halftime_score: '',
    match_hometeam_extra_score: '',
    match_awayteam_extra_score: '',
    match_hometeam_penalty_score: '',
    match_awayteam_penalty_score: '',
    match_hometeam_system: '',
    match_awayteam_system: '',
    match_live: '0',
    goalscorer: [],
    cards: [],
    substitutions: {
      home: [],
      away: [],
    },
    lineup: {
      home: {
        starting_lineups: [],
        substitutes: [],
        coach: [],
        missing_players: [],
      },
      away: {
        starting_lineups: [],
        substitutes: [],
        coach: [],
        missing_players: [],
      },
    },
    statistics: [],
  },
  {
    match_id: '182575',
    country_id: '68',
    country_name: 'Italy',
    league_id: '268',
    league_name: 'Serie D - Group A',
    match_date: '2019-03-03',
    match_status: 'Finished',
    match_time: '14:30',
    match_hometeam_id: '4256',
    match_hometeam_name: 'Andria',
    match_hometeam_score: '0',
    match_awayteam_name: 'Audace Cerignola',
    match_awayteam_id: '13220',
    match_awayteam_score: '1',
    match_hometeam_halftime_score: '',
    match_awayteam_halftime_score: '',
    match_hometeam_extra_score: '',
    match_awayteam_extra_score: '',
    match_hometeam_penalty_score: '',
    match_awayteam_penalty_score: '',
    match_hometeam_system: '',
    match_awayteam_system: '',
    match_live: '0',
    goalscorer: [],
    cards: [],
    substitutions: {
      home: [],
      away: [],
    },
    lineup: {
      home: {
        starting_lineups: [],
        substitutes: [],
        coach: [],
        missing_players: [],
      },
      away: {
        starting_lineups: [],
        substitutes: [],
        coach: [],
        missing_players: [],
      },
    },
    statistics: [],
  },
  {
    match_id: '182576',
    country_id: '68',
    country_name: 'Italy',
    league_id: '268',
    league_name: 'Serie D - Group A',
    match_date: '2019-03-03',
    match_status: 'Finished',
    match_time: '15:30',
    match_hometeam_id: '12594',
    match_hometeam_name: 'Citta di Fasano',
    match_hometeam_score: '2',
    match_awayteam_name: 'Gragnano',
    match_awayteam_id: '13222',
    match_awayteam_score: '1',
    match_hometeam_halftime_score: '',
    match_awayteam_halftime_score: '',
    match_hometeam_extra_score: '',
    match_awayteam_extra_score: '',
    match_hometeam_penalty_score: '',
    match_awayteam_penalty_score: '',
    match_hometeam_system: '',
    match_awayteam_system: '',
    match_live: '0',
    goalscorer: [],
    cards: [],
    substitutions: {
      home: [],
      away: [],
    },
    lineup: {
      home: {
        starting_lineups: [],
        substitutes: [],
        coach: [],
        missing_players: [],
      },
      away: {
        starting_lineups: [],
        substitutes: [],
        coach: [],
        missing_players: [],
      },
    },
    statistics: [],
  },
  {
    match_id: '182577',
    country_id: '68',
    country_name: 'Italy',
    league_id: '268',
    league_name: 'Serie D - Group A',
    match_date: '2019-03-03',
    match_status: 'Finished',
    match_time: '15:00',
    match_hometeam_id: '13215',
    match_hometeam_name: 'Gelbison Cilento',
    match_hometeam_score: '1',
    match_awayteam_name: 'Sorrento',
    match_awayteam_id: '13221',
    match_awayteam_score: '4',
    match_hometeam_halftime_score: '',
    match_awayteam_halftime_score: '',
    match_hometeam_extra_score: '',
    match_awayteam_extra_score: '',
    match_hometeam_penalty_score: '',
    match_awayteam_penalty_score: '',
    match_hometeam_system: '',
    match_awayteam_system: '',
    match_live: '0',
    goalscorer: [],
    cards: [],
    substitutions: {
      home: [],
      away: [],
    },
    lineup: {
      home: {
        starting_lineups: [],
        substitutes: [],
        coach: [],
        missing_players: [],
      },
      away: {
        starting_lineups: [],
        substitutes: [],
        coach: [],
        missing_players: [],
      },
    },
    statistics: [],
  },
  {
    match_id: '182578',
    country_id: '68',
    country_name: 'Italy',
    league_id: '268',
    league_name: 'Serie D - Group A',
    match_date: '2019-03-03',
    match_status: 'Finished',
    match_time: '15:00',
    match_hometeam_id: '13216',
    match_hometeam_name: 'Gravina',
    match_hometeam_score: '2',
    match_awayteam_name: 'Taranto',
    match_awayteam_id: '9214',
    match_awayteam_score: '0',
    match_hometeam_halftime_score: '',
    match_awayteam_halftime_score: '',
    match_hometeam_extra_score: '',
    match_awayteam_extra_score: '',
    match_hometeam_penalty_score: '',
    match_awayteam_penalty_score: '',
    match_hometeam_system: '',
    match_awayteam_system: '',
    match_live: '0',
    goalscorer: [],
    cards: [],
    substitutions: {
      home: [],
      away: [],
    },
    lineup: {
      home: {
        starting_lineups: [],
        substitutes: [],
        coach: [],
        missing_players: [],
      },
      away: {
        starting_lineups: [],
        substitutes: [],
        coach: [],
        missing_players: [],
      },
    },
    statistics: [],
  },
  {
    match_id: '182579',
    country_id: '68',
    country_name: 'Italy',
    league_id: '268',
    league_name: 'Serie D - Group A',
    match_date: '2019-03-03',
    match_status: 'Finished',
    match_time: '15:00',
    match_hometeam_id: '13049',
    match_hometeam_name: 'Sarnese',
    match_hometeam_score: '1',
    match_awayteam_name: 'Francavilla',
    match_awayteam_id: '9969',
    match_awayteam_score: '0',
    match_hometeam_halftime_score: '',
    match_awayteam_halftime_score: '',
    match_hometeam_extra_score: '',
    match_awayteam_extra_score: '',
    match_hometeam_penalty_score: '',
    match_awayteam_penalty_score: '',
    match_hometeam_system: '',
    match_awayteam_system: '',
    match_live: '0',
    goalscorer: [],
    cards: [],
    substitutions: {
      home: [],
      away: [],
    },
    lineup: {
      home: {
        starting_lineups: [],
        substitutes: [],
        coach: [],
        missing_players: [],
      },
      away: {
        starting_lineups: [],
        substitutes: [],
        coach: [],
        missing_players: [],
      },
    },
    statistics: [],
  },
  {
    match_id: '182580',
    country_id: '68',
    country_name: 'Italy',
    league_id: '268',
    league_name: 'Serie D - Group A',
    match_date: '2019-03-03',
    match_status: 'Finished',
    match_time: '15:00',
    match_hometeam_id: '14025',
    match_hometeam_name: 'SS Nola 1925',
    match_hometeam_score: '1',
    match_awayteam_name: 'Savoia',
    match_awayteam_id: '13218',
    match_awayteam_score: '0',
    match_hometeam_halftime_score: '',
    match_awayteam_halftime_score: '',
    match_hometeam_extra_score: '',
    match_awayteam_extra_score: '',
    match_hometeam_penalty_score: '',
    match_awayteam_penalty_score: '',
    match_hometeam_system: '',
    match_awayteam_system: '',
    match_live: '0',
    goalscorer: [],
    cards: [],
    substitutions: {
      home: [],
      away: [],
    },
    lineup: {
      home: {
        starting_lineups: [],
        substitutes: [],
        coach: [],
        missing_players: [],
      },
      away: {
        starting_lineups: [],
        substitutes: [],
        coach: [],
        missing_players: [],
      },
    },
    statistics: [],
  },
  {
    match_id: '182581',
    country_id: '68',
    country_name: 'Italy',
    league_id: '268',
    league_name: 'Serie D - Group A',
    match_date: '2019-03-03',
    match_status: 'Finished',
    match_time: '14:30',
    match_hometeam_id: '13224',
    match_hometeam_name: 'Vesuvio Ercolanese',
    match_hometeam_score: '1',
    match_awayteam_name: 'Picerno',
    match_awayteam_id: '11639',
    match_awayteam_score: '2',
    match_hometeam_halftime_score: '',
    match_awayteam_halftime_score: '',
    match_hometeam_extra_score: '',
    match_awayteam_extra_score: '',
    match_hometeam_penalty_score: '',
    match_awayteam_penalty_score: '',
    match_hometeam_system: '',
    match_awayteam_system: '',
    match_live: '0',
    goalscorer: [],
    cards: [],
    substitutions: {
      home: [],
      away: [],
    },
    lineup: {
      home: {
        starting_lineups: [],
        substitutes: [],
        coach: [],
        missing_players: [],
      },
      away: {
        starting_lineups: [],
        substitutes: [],
        coach: [],
        missing_players: [],
      },
    },
    statistics: [],
  },
  {
    match_id: '182584',
    country_id: '68',
    country_name: 'Italy',
    league_id: '268',
    league_name: 'Serie D - Group A',
    match_date: '2019-03-03',
    match_status: 'Finished',
    match_time: '14:30',
    match_hometeam_id: '13240',
    match_hometeam_name: 'Citta di Messina',
    match_hometeam_score: '1',
    match_awayteam_name: 'Bari',
    match_awayteam_id: '4194',
    match_awayteam_score: '3',
    match_hometeam_halftime_score: '',
    match_awayteam_halftime_score: '',
    match_hometeam_extra_score: '',
    match_awayteam_extra_score: '',
    match_hometeam_penalty_score: '',
    match_awayteam_penalty_score: '',
    match_hometeam_system: '',
    match_awayteam_system: '',
    match_live: '0',
    goalscorer: [],
    cards: [],
    substitutions: {
      home: [],
      away: [],
    },
    lineup: {
      home: {
        starting_lineups: [],
        substitutes: [],
        coach: [],
        missing_players: [],
      },
      away: {
        starting_lineups: [],
        substitutes: [],
        coach: [],
        missing_players: [],
      },
    },
    statistics: [],
  },
  {
    match_id: '182585',
    country_id: '68',
    country_name: 'Italy',
    league_id: '268',
    league_name: 'Serie D - Group A',
    match_date: '2019-03-03',
    match_status: 'Finished',
    match_time: '15:00',
    match_hometeam_id: '13225',
    match_hometeam_name: 'Gela',
    match_hometeam_score: '0',
    match_awayteam_name: 'Messina',
    match_awayteam_id: '13227',
    match_awayteam_score: '1',
    match_hometeam_halftime_score: '',
    match_awayteam_halftime_score: '',
    match_hometeam_extra_score: '',
    match_awayteam_extra_score: '',
    match_hometeam_penalty_score: '',
    match_awayteam_penalty_score: '',
    match_hometeam_system: '',
    match_awayteam_system: '',
    match_live: '0',
    goalscorer: [],
    cards: [],
    substitutions: {
      home: [],
      away: [],
    },
    lineup: {
      home: {
        starting_lineups: [],
        substitutes: [],
        coach: [],
        missing_players: [],
      },
      away: {
        starting_lineups: [],
        substitutes: [],
        coach: [],
        missing_players: [],
      },
    },
    statistics: [],
  },
  {
    match_id: '182586',
    country_id: '68',
    country_name: 'Italy',
    league_id: '268',
    league_name: 'Serie D - Group A',
    match_date: '2019-03-03',
    match_status: 'Finished',
    match_time: '14:30',
    match_hometeam_id: '13226',
    match_hometeam_name: 'Igea Virtus',
    match_hometeam_score: '0',
    match_awayteam_name: 'Troina',
    match_awayteam_id: '13237',
    match_awayteam_score: '1',
    match_hometeam_halftime_score: '',
    match_awayteam_halftime_score: '',
    match_hometeam_extra_score: '',
    match_awayteam_extra_score: '',
    match_hometeam_penalty_score: '',
    match_awayteam_penalty_score: '',
    match_hometeam_system: '',
    match_awayteam_system: '',
    match_live: '0',
    goalscorer: [],
    cards: [],
    substitutions: {
      home: [],
      away: [],
    },
    lineup: {
      home: {
        starting_lineups: [],
        substitutes: [],
        coach: [],
        missing_players: [],
      },
      away: {
        starting_lineups: [],
        substitutes: [],
        coach: [],
        missing_players: [],
      },
    },
    statistics: [],
  },
  {
    match_id: '182587',
    country_id: '68',
    country_name: 'Italy',
    league_id: '268',
    league_name: 'Serie D - Group A',
    match_date: '2019-03-03',
    match_status: 'Finished',
    match_time: '14:30',
    match_hometeam_id: '13229',
    match_hometeam_name: 'Locri 1909',
    match_hometeam_score: '1',
    match_awayteam_name: 'Marsala',
    match_awayteam_id: '13234',
    match_awayteam_score: '4',
    match_hometeam_halftime_score: '',
    match_awayteam_halftime_score: '',
    match_hometeam_extra_score: '',
    match_awayteam_extra_score: '',
    match_hometeam_penalty_score: '',
    match_awayteam_penalty_score: '',
    match_hometeam_system: '',
    match_awayteam_system: '',
    match_live: '0',
    goalscorer: [],
    cards: [],
    substitutions: {
      home: [],
      away: [],
    },
    lineup: {
      home: {
        starting_lineups: [],
        substitutes: [],
        coach: [],
        missing_players: [],
      },
      away: {
        starting_lineups: [],
        substitutes: [],
        coach: [],
        missing_players: [],
      },
    },
    statistics: [],
  },
  {
    match_id: '182588',
    country_id: '68',
    country_name: 'Italy',
    league_id: '268',
    league_name: 'Serie D - Group A',
    match_date: '2019-03-03',
    match_status: 'Finished',
    match_time: '15:00',
    match_hometeam_id: '13228',
    match_hometeam_name: 'Nocerina',
    match_hometeam_score: '2',
    match_awayteam_name: 'Roccella',
    match_awayteam_id: '9131',
    match_awayteam_score: '0',
    match_hometeam_halftime_score: '',
    match_awayteam_halftime_score: '',
    match_hometeam_extra_score: '',
    match_awayteam_extra_score: '',
    match_hometeam_penalty_score: '',
    match_awayteam_penalty_score: '',
    match_hometeam_system: '',
    match_awayteam_system: '',
    match_live: '0',
    goalscorer: [],
    cards: [],
    substitutions: {
      home: [],
      away: [],
    },
    lineup: {
      home: {
        starting_lineups: [],
        substitutes: [],
        coach: [],
        missing_players: [],
      },
      away: {
        starting_lineups: [],
        substitutes: [],
        coach: [],
        missing_players: [],
      },
    },
    statistics: [],
  },
  {
    match_id: '182589',
    country_id: '68',
    country_name: 'Italy',
    league_id: '268',
    league_name: 'Serie D - Group A',
    match_date: '2019-03-03',
    match_status: 'Finished',
    match_time: '14:30',
    match_hometeam_id: '13230',
    match_hometeam_name: 'Portici 1906',
    match_hometeam_score: '1',
    match_awayteam_name: 'Rotonda',
    match_awayteam_id: '13233',
    match_awayteam_score: '0',
    match_hometeam_halftime_score: '',
    match_awayteam_halftime_score: '',
    match_hometeam_extra_score: '',
    match_awayteam_extra_score: '',
    match_hometeam_penalty_score: '',
    match_awayteam_penalty_score: '',
    match_hometeam_system: '',
    match_awayteam_system: '',
    match_live: '0',
    goalscorer: [],
    cards: [],
    substitutions: {
      home: [],
      away: [],
    },
    lineup: {
      home: {
        starting_lineups: [],
        substitutes: [],
        coach: [],
        missing_players: [],
      },
      away: {
        starting_lineups: [],
        substitutes: [],
        coach: [],
        missing_players: [],
      },
    },
    statistics: [],
  },
  {
    match_id: '182590',
    country_id: '68',
    country_name: 'Italy',
    league_id: '268',
    league_name: 'Serie D - Group A',
    match_date: '2019-03-03',
    match_status: 'Finished',
    match_time: '14:30',
    match_hometeam_id: '13239',
    match_hometeam_name: 'US Palmese',
    match_hometeam_score: '1',
    match_awayteam_name: 'Sancataldese',
    match_awayteam_id: '13235',
    match_awayteam_score: '0',
    match_hometeam_halftime_score: '',
    match_awayteam_halftime_score: '',
    match_hometeam_extra_score: '',
    match_awayteam_extra_score: '',
    match_hometeam_penalty_score: '',
    match_awayteam_penalty_score: '',
    match_hometeam_system: '',
    match_awayteam_system: '',
    match_live: '0',
    goalscorer: [],
    cards: [],
    substitutions: {
      home: [],
      away: [],
    },
    lineup: {
      home: {
        starting_lineups: [],
        substitutes: [],
        coach: [],
        missing_players: [],
      },
      away: {
        starting_lineups: [],
        substitutes: [],
        coach: [],
        missing_players: [],
      },
    },
    statistics: [],
  },
];
