export default [{
  match_id: '226059',
  country_id: '20',
  country_name: 'Bulgaria',
  league_id: '84',
  league_name: 'Super Cup',
  match_date: '2019-07-03',
  match_status: 'Finished',
  match_time: '19:30',
  match_hometeam_id: '1669',
  match_hometeam_name: 'Ludogorets',
  match_hometeam_score: '2',
  match_awayteam_name: 'Lok. Plovdiv',
  match_awayteam_id: '1680',
  match_awayteam_score: '0',
  match_hometeam_halftime_score: '1',
  match_awayteam_halftime_score: '0',
  match_hometeam_extra_score: '1',
  match_awayteam_extra_score: '0',
  match_hometeam_penalty_score: '',
  match_awayteam_penalty_score: '',
  match_hometeam_system: '4 - 2 - 3 - 1',
  match_awayteam_system: '3 - 5 - 2',
  match_live: '0',
  goalscorer: [
    {
      time: '4',
      home_scorer: 'Tchibota M.',
      score: '1 - 0',
      away_scorer: '',
    },
    {
      time: '90+3',
      home_scorer: 'Lukoki J.',
      score: '2 - 0',
      away_scorer: '',
    },
  ],
  cards: [
    {
      time: '7',
      home_fault: 'Goralski J.',
      card: 'yellow card',
      away_fault: '',
    },
    {
      time: '11',
      home_fault: '',
      card: 'yellow card',
      away_fault: 'Eze S.',
    },
    {
      time: '44',
      home_fault: '',
      card: 'yellow card',
      away_fault: 'Umarbaev P.',
    },
    {
      time: '48',
      home_fault: '',
      card: 'yellow card',
      away_fault: 'Tomasevic J.',
    },
    {
      time: '68',
      home_fault: 'Lukoki J.',
      card: 'yellow card',
      away_fault: '',
    },
    {
      time: '68',
      home_fault: '',
      card: 'yellow card',
      away_fault: 'Ozbolt A.',
    },
    {
      time: '76',
      home_fault: 'Grigore D.',
      card: 'yellow card',
      away_fault: '',
    },
    {
      time: '89',
      home_fault: 'Cicinho',
      card: 'yellow card',
      away_fault: '',
    },
    {
      time: '90',
      home_fault: '',
      card: 'yellow card',
      away_fault: 'Bahtic E.',
    },
  ],
  substitutions: {
    home: [
      {
        time: '46',
        substitution: 'Nedyalkov A. | Moti C.',
      },
      {
        time: '61',
        substitution: 'Keseru C. | Biton D.',
      },
      {
        time: '84',
        substitution: 'Marcelinho | Bakalov D.',
      },
    ],
    away: [
      {
        time: '66',
        substitution: 'Aralica A. | Ozbolt A.',
      },
      {
        time: '74',
        substitution: 'Umarbaev P. | Eliton Junior',
      },
      {
        time: '75',
        substitution: 'Iliev Rusev G. | Bahtic E.',
      },
    ],
  },
  lineup: {
    home: {
      starting_lineups: [
        {
          lineup_player: 'Cicinho',
          lineup_number: '4',
          lineup_position: '2',
        },
        {
          lineup_player: 'Dyakov S.',
          lineup_number: '18',
          lineup_position: '6',
        },
        {
          lineup_player: 'Goralski J.',
          lineup_number: '44',
          lineup_position: '7',
        },
        {
          lineup_player: 'Grigore D.',
          lineup_number: '21',
          lineup_position: '4',
        },
        {
          lineup_player: 'Ikoko J.',
          lineup_number: '22',
          lineup_position: '5',
        },
        {
          lineup_player: 'Iliev Ivanov P. (G)',
          lineup_number: '23',
          lineup_position: '1',
        },
        {
          lineup_player: 'Keseru C.',
          lineup_number: '28',
          lineup_position: '11',
        },
        {
          lineup_player: 'Lukoki J.',
          lineup_number: '92',
          lineup_position: '8',
        },
        {
          lineup_player: 'Marcelinho',
          lineup_number: '84',
          lineup_position: '9',
        },
        {
          lineup_player: 'Nedyalkov A.',
          lineup_number: '3',
          lineup_position: '3',
        },
        {
          lineup_player: 'Tchibota M.',
          lineup_number: '13',
          lineup_position: '10',
        },
      ],
      substitutes: [
        {
          lineup_player: 'Bakalov D.',
          lineup_number: '7',
          lineup_position: '',
        },
        {
          lineup_player: 'Biton D.',
          lineup_number: '8',
          lineup_position: '',
        },
        {
          lineup_player: 'Manolev S.',
          lineup_number: '11',
          lineup_position: '',
        },
        {
          lineup_player: 'Moti C.',
          lineup_number: '30',
          lineup_position: '',
        },
        {
          lineup_player: 'Renan (G)',
          lineup_number: '33',
          lineup_position: '',
        },
        {
          lineup_player: 'Terziev G.',
          lineup_number: '5',
          lineup_position: '',
        },
        {
          lineup_player: 'Yusein S.',
          lineup_number: '20',
          lineup_position: '',
        },
      ],
      coach: [
        {
          lineup_player: 'Stoev S.',
          lineup_number: '-1',
          lineup_position: '',
        },
      ],
      missing_players: [],
    },
    away: {
      starting_lineups: [
        {
          lineup_player: 'Aralica A.',
          lineup_number: '77',
          lineup_position: '10',
        },
        {
          lineup_player: 'Eze S.',
          lineup_number: '6',
          lineup_position: '2',
        },
        {
          lineup_player: 'Iliev D.',
          lineup_number: '14',
          lineup_position: '11',
        },
        {
          lineup_player: 'Iliev Rusev G.',
          lineup_number: '91',
          lineup_position: '8',
        },
        {
          lineup_player: 'Karageren B.',
          lineup_number: '9',
          lineup_position: '9',
        },
        {
          lineup_player: 'Lukov M. (G)',
          lineup_number: '71',
          lineup_position: '1',
        },
        {
          lineup_player: 'Petrovic M.',
          lineup_number: '20',
          lineup_position: '4',
        },
        {
          lineup_player: 'Tomasevic J.',
          lineup_number: '50',
          lineup_position: '3',
        },
        {
          lineup_player: 'Tsvetanov M.',
          lineup_number: '7',
          lineup_position: '7',
        },
        {
          lineup_player: 'Umarbaev P.',
          lineup_number: '10',
          lineup_position: '6',
        },
        {
          lineup_player: 'Vitanov P.',
          lineup_number: '34',
          lineup_position: '5',
        },
      ],
      substitutes: [
        {
          lineup_player: 'Arhan I.',
          lineup_number: '15',
          lineup_position: '',
        },
        {
          lineup_player: 'Bahtic E.',
          lineup_number: '13',
          lineup_position: '',
        },
        {
          lineup_player: 'Kolev F.',
          lineup_number: '19',
          lineup_position: '',
        },
        {
          lineup_player: 'Ozbolt A.',
          lineup_number: '12',
          lineup_position: '',
        },
        {
          lineup_player: 'Pirgov I. (G)',
          lineup_number: '1',
          lineup_position: '',
        },
        {
          lineup_player: 'Eliton Junior',
          lineup_number: '61',
          lineup_position: '',
        },
        {
          lineup_player: 'Yusein O.',
          lineup_number: '29',
          lineup_position: '',
        },
      ],
      coach: [
        {
          lineup_player: 'Akrapovic B.',
          lineup_number: '-1',
          lineup_position: '',
        },
      ],
      missing_players: [],
    },
  },
  statistics: [
    {
      type: 'Ball Possession',
      home: '46%',
      away: '54%',
    },
    {
      type: 'Goal Attempts',
      home: '15',
      away: '18',
    },
    {
      type: 'Shots on Goal',
      home: '7',
      away: '8',
    },
    {
      type: 'Shots off Goal',
      home: '8',
      away: '10',
    },
    {
      type: 'Free Kicks',
      home: '26',
      away: '25',
    },
    {
      type: 'Corner Kicks',
      home: '5',
      away: '3',
    },
    {
      type: 'Throw-in',
      home: '18',
      away: '25',
    },
    {
      type: 'Goalkeeper Saves',
      home: '8',
      away: '5',
    },
    {
      type: 'Yellow Cards',
      home: '4',
      away: '5',
    },
    {
      type: 'Attacks',
      home: '88',
      away: '99',
    },
    {
      type: 'Dangerous Attacks',
      home: '65',
      away: '86',
    },
  ],
},
{
  match_id: '229170',
  country_id: '50',
  country_name: 'Georgia',
  league_id: '192',
  league_name: 'Crystalbet Erovnuli Liga',
  match_date: '2019-07-03',
  match_status: 'Finished',
  match_time: '17:00',
  match_hometeam_id: '3195',
  match_hometeam_name: 'Dila Gori',
  match_hometeam_score: '2',
  match_awayteam_name: 'Bolnisi',
  match_awayteam_id: '3207',
  match_awayteam_score: '0',
  match_hometeam_halftime_score: '1',
  match_awayteam_halftime_score: '0',
  match_hometeam_extra_score: '1',
  match_awayteam_extra_score: '0',
  match_hometeam_penalty_score: '',
  match_awayteam_penalty_score: '',
  match_hometeam_system: '4 - 2 - 3 - 1',
  match_awayteam_system: '4 - 2 - 3 - 1',
  match_live: '0',
  goalscorer: [
    {
      time: '44',
      home_scorer: 'Fortes A.',
      score: '1 - 0',
      away_scorer: '',
    },
    {
      time: '90+1',
      home_scorer: 'Goshteliani G.',
      score: '2 - 0',
      away_scorer: '',
    },
  ],
  cards: [
    {
      time: '43',
      home_fault: '',
      card: 'yellow card',
      away_fault: 'Tarkhnishvili T.',
    },
    {
      time: '43',
      home_fault: '',
      card: 'yellow card',
      away_fault: 'Ugulava J.',
    },
    {
      time: '84',
      home_fault: '',
      card: 'yellow card',
      away_fault: 'Ugrekhelidze L.',
    },
  ],
  substitutions: {
    home: [
      {
        time: '71',
        substitution: 'Kutsia G. | Nondi A.',
      },
      {
        time: '90',
        substitution: 'Kougbenya D. | Spanderashvili N.',
      },
    ],
    away: [
      {
        time: '64',
        substitution: 'Kirkitadze D. | Targamadze D.',
      },
      {
        time: '77',
        substitution: 'Ugulava J. | Sikharulia Z.',
      },
    ],
  },
  lineup: {
    home: {
      starting_lineups: [
        {
          lineup_player: 'Begashvili G. (G)',
          lineup_number: '21',
          lineup_position: '1',
        },
        {
          lineup_player: 'Chaduneli G.',
          lineup_number: '4',
          lineup_position: '4',
        },
        {
          lineup_player: 'Fortes A.',
          lineup_number: '9',
          lineup_position: '8',
        },
        {
          lineup_player: 'Giorbelidze G.',
          lineup_number: '2',
          lineup_position: '5',
        },
        {
          lineup_player: 'Goshteliani G.',
          lineup_number: '25',
          lineup_position: '11',
        },
        {
          lineup_player: 'Grigalashvili T.',
          lineup_number: '33',
          lineup_position: '2',
        },
        {
          lineup_player: 'Kougbenya D.',
          lineup_number: '8',
          lineup_position: '9',
        },
        {
          lineup_player: 'Kutsia G.',
          lineup_number: '10',
          lineup_position: '6',
        },
        {
          lineup_player: 'Mirtskhulava B.',
          lineup_number: '3',
          lineup_position: '3',
        },
        {
          lineup_player: 'Nonikashvili L.',
          lineup_number: '11',
          lineup_position: '10',
        },
        {
          lineup_player: 'Razmadze L. (C)',
          lineup_number: '7',
          lineup_position: '7',
        },
      ],
      substitutes: [
        {
          lineup_player: 'Kereleishvili Z.',
          lineup_number: '17',
          lineup_position: '',
        },
        {
          lineup_player: 'Lamptey I.',
          lineup_number: '23',
          lineup_position: '',
        },
        {
          lineup_player: 'Mamulashvili G.',
          lineup_number: '5',
          lineup_position: '',
        },
        {
          lineup_player: 'Nondi A.',
          lineup_number: '6',
          lineup_position: '',
        },
        {
          lineup_player: 'Spanderashvili N.',
          lineup_number: '13',
          lineup_position: '',
        },
        {
          lineup_player: 'Titvinidze L. (G)',
          lineup_number: '1',
          lineup_position: '',
        },
        {
          lineup_player: 'Felipe Paim',
          lineup_number: '37',
          lineup_position: '',
        },
      ],
      coach: [],
      missing_players: [],
    },
    away: {
      starting_lineups: [
        {
          lineup_player: 'Chachua R.',
          lineup_number: '2',
          lineup_position: '2',
        },
        {
          lineup_player: 'Goshadze O. (G)',
          lineup_number: '30',
          lineup_position: '1',
        },
        {
          lineup_player: 'Gvaradze B.',
          lineup_number: '29',
          lineup_position: '9',
        },
        {
          lineup_player: 'Isiani V. (C)',
          lineup_number: '24',
          lineup_position: '10',
        },
        {
          lineup_player: 'Khetsuriani G.',
          lineup_number: '17',
          lineup_position: '3',
        },
        {
          lineup_player: 'Kirkitadze D.',
          lineup_number: '11',
          lineup_position: '8',
        },
        {
          lineup_player: 'Sukhiashvili A.',
          lineup_number: '27',
          lineup_position: '5',
        },
        {
          lineup_player: 'Tarkhnishvili T.',
          lineup_number: '7',
          lineup_position: '7',
        },
        {
          lineup_player: 'Tsatskrialashvili R.',
          lineup_number: '23',
          lineup_position: '6',
        },
        {
          lineup_player: 'Ugrekhelidze L.',
          lineup_number: '4',
          lineup_position: '4',
        },
        {
          lineup_player: 'Ugulava J.',
          lineup_number: '10',
          lineup_position: '11',
        },
      ],
      substitutes: [
        {
          lineup_player: 'Isiani L. (G)',
          lineup_number: '12',
          lineup_position: '',
        },
        {
          lineup_player: 'Khvadagiani G.',
          lineup_number: '21',
          lineup_position: '',
        },
        {
          lineup_player: 'Kikava V.',
          lineup_number: '6',
          lineup_position: '',
        },
        {
          lineup_player: 'Saganelidze A.',
          lineup_number: '14',
          lineup_position: '',
        },
        {
          lineup_player: 'Sikharulia Z.',
          lineup_number: '19',
          lineup_position: '',
        },
        {
          lineup_player: 'Targamadze D.',
          lineup_number: '20',
          lineup_position: '',
        },
        {
          lineup_player: 'Tvildiani A.',
          lineup_number: '5',
          lineup_position: '',
        },
      ],
      coach: [],
      missing_players: [],
    },
  },
  statistics: [],
},
{
  match_id: '229171',
  country_id: '50',
  country_name: 'Georgia',
  league_id: '192',
  league_name: 'Crystalbet Erovnuli Liga',
  match_date: '2019-07-03',
  match_status: 'Finished',
  match_time: '19:00',
  match_hometeam_id: '3194',
  match_hometeam_name: 'Dinamo Tbilisi',
  match_hometeam_score: '2',
  match_awayteam_name: 'Dinamo Batumi',
  match_awayteam_id: '3190',
  match_awayteam_score: '1',
  match_hometeam_halftime_score: '1',
  match_awayteam_halftime_score: '1',
  match_hometeam_extra_score: '1',
  match_awayteam_extra_score: '1',
  match_hometeam_penalty_score: '',
  match_awayteam_penalty_score: '',
  match_hometeam_system: '4 - 2 - 3 - 1',
  match_awayteam_system: '4 - 2 - 3 - 1',
  match_live: '0',
  goalscorer: [
    {
      time: '4',
      home_scorer: 'Papava G.',
      score: '1 - 0',
      away_scorer: '',
    },
    {
      time: '26',
      home_scorer: '',
      score: '1 - 1',
      away_scorer: 'Flamarion',
    },
    {
      time: '82',
      home_scorer: 'Kutalia L.',
      score: '2 - 1',
      away_scorer: '',
    },
  ],
  cards: [
    {
      time: '38',
      home_fault: 'Kutalia L.',
      card: 'yellow card',
      away_fault: '',
    },
    {
      time: '44',
      home_fault: '',
      card: 'yellow card',
      away_fault: 'Chaladze L.',
    },
    {
      time: '61',
      home_fault: '',
      card: 'yellow card',
      away_fault: 'Kobakhidze M.',
    },
    {
      time: '63',
      home_fault: 'Kobouri D.',
      card: 'yellow card',
      away_fault: '',
    },
    {
      time: '90+4',
      home_fault: '',
      card: 'yellow card',
      away_fault: 'Teidi B.',
    },
  ],
  substitutions: {
    home: [
      {
        time: '73',
        substitution: 'Shulaia A. | Daffe A.',
      },
      {
        time: '86',
        substitution: 'Kavtaradze N. | Kardava B.',
      },
      {
        time: '90+2',
        substitution: 'Shengelia L. | Kukhianidze G.',
      },
    ],
    away: [
      {
        time: '46',
        substitution: 'Sabanadze N. | Dvalishvili V.',
      },
      {
        time: '85',
        substitution: 'Mamuchashvili V. | Iluridze G.',
      },
      {
        time: '90+2',
        substitution: 'Mandzhgaladze G. | Tevdoradze V.',
      },
    ],
  },
  lineup: {
    home: {
      starting_lineups: [
        {
          lineup_player: 'Iashvili N.',
          lineup_number: '24',
          lineup_position: '2',
        },
        {
          lineup_player: 'Kavtaradze N.',
          lineup_number: '38',
          lineup_position: '9',
        },
        {
          lineup_player: 'Kimadze G.',
          lineup_number: '16',
          lineup_position: '5',
        },
        {
          lineup_player: 'Kobouri D.',
          lineup_number: '5',
          lineup_position: '4',
        },
        {
          lineup_player: 'Kutalia L.',
          lineup_number: '19',
          lineup_position: '11',
        },
        {
          lineup_player: 'Mongil V.',
          lineup_number: '3',
          lineup_position: '3',
        },
        {
          lineup_player: 'Ninua N.',
          lineup_number: '32',
          lineup_position: '6',
        },
        {
          lineup_player: 'Papava G.',
          lineup_number: '15',
          lineup_position: '7',
        },
        {
          lineup_player: 'Perales J. (G)',
          lineup_number: '1',
          lineup_position: '1',
        },
        {
          lineup_player: 'Shengelia L. (C)',
          lineup_number: '27',
          lineup_position: '10',
        },
        {
          lineup_player: 'Shulaia A.',
          lineup_number: '11',
          lineup_position: '8',
        },
      ],
      substitutes: [
        {
          lineup_player: 'Azarovi I.',
          lineup_number: '23',
          lineup_position: '',
        },
        {
          lineup_player: 'Daffe A.',
          lineup_number: '14',
          lineup_position: '',
        },
        {
          lineup_player: 'Kardava B.',
          lineup_number: '6',
          lineup_position: '',
        },
        {
          lineup_player: 'Kukhianidze G.',
          lineup_number: '8',
          lineup_position: '',
        },
        {
          lineup_player: 'Kutaladze L. (G)',
          lineup_number: '25',
          lineup_position: '',
        },
        {
          lineup_player: 'Rukhaia G.',
          lineup_number: '2',
          lineup_position: '',
        },
        {
          lineup_player: 'Zaria G.',
          lineup_number: '7',
          lineup_position: '',
        },
      ],
      coach: [],
      missing_players: [],
    },
    away: {
      starting_lineups: [
        {
          lineup_player: 'Alavidze M. (G) (C)',
          lineup_number: '12',
          lineup_position: '1',
        },
        {
          lineup_player: 'Chaladze L.',
          lineup_number: '33',
          lineup_position: '5',
        },
        {
          lineup_player: 'Flamarion',
          lineup_number: '16',
          lineup_position: '9',
        },
        {
          lineup_player: 'Gagoshidze M.',
          lineup_number: '24',
          lineup_position: '4',
        },
        {
          lineup_player: 'Gegetchkori L.',
          lineup_number: '18',
          lineup_position: '2',
        },
        {
          lineup_player: 'Kobakhidze M.',
          lineup_number: '20',
          lineup_position: '3',
        },
        {
          lineup_player: 'Mamuchashvili V.',
          lineup_number: '17',
          lineup_position: '7',
        },
        {
          lineup_player: 'Mandzhgaladze G.',
          lineup_number: '13',
          lineup_position: '10',
        },
        {
          lineup_player: 'Ramos G.',
          lineup_number: '30',
          lineup_position: '8',
        },
        {
          lineup_player: 'Sabanadze N.',
          lineup_number: '14',
          lineup_position: '11',
        },
        {
          lineup_player: 'Teidi B.',
          lineup_number: '3',
          lineup_position: '6',
        },
      ],
      substitutes: [
        {
          lineup_player: 'Adamadze G.',
          lineup_number: '4',
          lineup_position: '',
        },
        {
          lineup_player: 'Dvalishvili V.',
          lineup_number: '21',
          lineup_position: '',
        },
        {
          lineup_player: 'Iluridze G.',
          lineup_number: '11',
          lineup_position: '',
        },
        {
          lineup_player: 'Meliava K.',
          lineup_number: '23',
          lineup_position: '',
        },
        {
          lineup_player: 'Patsatsia V.',
          lineup_number: '28',
          lineup_position: '',
        },
        {
          lineup_player: 'Shovnadze L. (G)',
          lineup_number: '19',
          lineup_position: '',
        },
        {
          lineup_player: 'Tevdoradze V.',
          lineup_number: '10',
          lineup_position: '',
        },
      ],
      coach: [],
      missing_players: [],
    },
  },
  statistics: [],
},
{
  match_id: '229697',
  country_id: '63',
  country_name: 'Indonesia',
  league_id: '244',
  league_name: 'Liga 1',
  match_date: '2019-07-03',
  match_status: 'Finished',
  match_time: '10:30',
  match_hometeam_id: '3941',
  match_hometeam_name: 'Persija Jakarta',
  match_hometeam_score: '1',
  match_awayteam_name: 'PSS Sleman',
  match_awayteam_id: '3980',
  match_awayteam_score: '0',
  match_hometeam_halftime_score: '1',
  match_awayteam_halftime_score: '0',
  match_hometeam_extra_score: '1',
  match_awayteam_extra_score: '0',
  match_hometeam_penalty_score: '',
  match_awayteam_penalty_score: '',
  match_hometeam_system: '',
  match_awayteam_system: '',
  match_live: '0',
  goalscorer: [
    {
      time: '25',
      home_scorer: 'Simic M.',
      score: '1 - 0',
      away_scorer: '',
    },
  ],
  cards: [
    {
      time: '18',
      home_fault: '',
      card: 'yellow card',
      away_fault: 'Perkasa R.',
    },
    {
      time: '69',
      home_fault: 'Sandi',
      card: 'yellow card',
      away_fault: '',
    },
    {
      time: '90',
      home_fault: '',
      card: 'yellow card',
      away_fault: 'Mustaine D.',
    },
    {
      time: '90+5',
      home_fault: '',
      card: 'yellow card',
      away_fault: 'de la Cruz A.',
    },
  ],
  substitutions: {
    home: [
      {
        time: '46',
        substitution: 'Putra F. E. | Ridwan F.',
      },
      {
        time: '80',
        substitution: 'Sandi | Nasadit Y.',
      },
    ],
    away: [
      {
        time: '67',
        substitution: 'Kambuaya R. | Mustaine D.',
      },
      {
        time: '83',
        substitution: 'Ferreira B. | Milla Z.',
      },
    ],
  },
  lineup: {
    home: {
      starting_lineups: [
        {
          lineup_player: 'Ginanjar S. (G)',
          lineup_number: '88',
          lineup_position: '',
        },
        {
          lineup_player: 'Abdurahman M. (C)',
          lineup_number: '6',
          lineup_position: '',
        },
        {
          lineup_player: 'Bruno',
          lineup_number: '10',
          lineup_position: '',
        },
        {
          lineup_player: 'Chand R.',
          lineup_number: '32',
          lineup_position: '',
        },
        {
          lineup_player: 'Putra F. E.',
          lineup_number: '41',
          lineup_position: '',
        },
        {
          lineup_player: 'Saputra D.',
          lineup_number: '3',
          lineup_position: '',
        },
        {
          lineup_player: 'Setiawan N.',
          lineup_number: '11',
          lineup_position: '',
        },
        {
          lineup_player: 'Simanjuntak R.',
          lineup_number: '25',
          lineup_position: '',
        },
        {
          lineup_player: 'Simic M.',
          lineup_number: '9',
          lineup_position: '',
        },
        {
          lineup_player: 'Sucipto T.',
          lineup_number: '16',
          lineup_position: '',
        },
        {
          lineup_player: 'Sandi',
          lineup_number: '45',
          lineup_position: '',
        },
      ],
      substitutes: [
        {
          lineup_player: 'Ardhiyasa A. (G)',
          lineup_number: '26',
          lineup_position: '',
        },
        {
          lineup_player: 'Hehanusa R.',
          lineup_number: '40',
          lineup_position: '',
        },
        {
          lineup_player: 'Nasadit Y.',
          lineup_number: '8',
          lineup_position: '',
        },
        {
          lineup_player: 'Pamungkas B.',
          lineup_number: '20',
          lineup_position: '',
        },
        {
          lineup_player: 'Ridwan F.',
          lineup_number: '17',
          lineup_position: '',
        },
        {
          lineup_player: 'Sofyan I.',
          lineup_number: '14',
          lineup_position: '',
        },
        {
          lineup_player: 'Witriawan R. F.',
          lineup_number: '24',
          lineup_position: '',
        },
      ],
      coach: [
        {
          lineup_player: 'Banuelos J.',
          lineup_number: '-1',
          lineup_position: '',
        },
      ],
      missing_players: [],
    },
    away: {
      starting_lineups: [
        {
          lineup_player: 'Pramana E. (G)',
          lineup_number: '21',
          lineup_position: '',
        },
        {
          lineup_player: 'Bokhashvili E.',
          lineup_number: '10',
          lineup_position: '',
        },
        {
          lineup_player: 'de la Cruz A.',
          lineup_number: '14',
          lineup_position: '',
        },
        {
          lineup_player: 'Ferreira B.',
          lineup_number: '32',
          lineup_position: '',
        },
        {
          lineup_player: 'Kambuaya R.',
          lineup_number: '7',
          lineup_position: '',
        },
        {
          lineup_player: 'Nirwanto B. (C)',
          lineup_number: '3',
          lineup_position: '',
        },
        {
          lineup_player: 'Perkasa R.',
          lineup_number: '15',
          lineup_position: '',
        },
        {
          lineup_player: 'Ramadhan A.',
          lineup_number: '5',
          lineup_position: '',
        },
        {
          lineup_player: 'Sukarta W.',
          lineup_number: '6',
          lineup_position: '',
        },
        {
          lineup_player: 'Sukmara J.',
          lineup_number: '18',
          lineup_position: '',
        },
        {
          lineup_player: 'Tuharea H.',
          lineup_number: '12',
          lineup_position: '',
        },
      ],
      substitutes: [
        {
          lineup_player: 'Alom N.',
          lineup_number: '8',
          lineup_position: '',
        },
        {
          lineup_player: 'Hamdani T. (G)',
          lineup_number: '34',
          lineup_position: '',
        },
        {
          lineup_player: 'Milla Z.',
          lineup_number: '27',
          lineup_position: '',
        },
        {
          lineup_player: 'Mustaine D.',
          lineup_number: '92',
          lineup_position: '',
        },
        {
          lineup_player: 'Pratomo P.',
          lineup_number: '22',
          lineup_position: '',
        },
        {
          lineup_player: 'Rachman D.',
          lineup_number: '69',
          lineup_position: '',
        },
        {
          lineup_player: 'Yudo K.',
          lineup_number: '99',
          lineup_position: '',
        },
      ],
      coach: [
        {
          lineup_player: 'Nurdiantoro S.',
          lineup_number: '-1',
          lineup_position: '',
        },
      ],
      missing_players: [],
    },
  },
  statistics: [
    {
      type: 'Ball Possession',
      home: '62%',
      away: '38%',
    },
    {
      type: 'Goal Attempts',
      home: '17',
      away: '14',
    },
    {
      type: 'Shots on Goal',
      home: '7',
      away: '4',
    },
    {
      type: 'Shots off Goal',
      home: '10',
      away: '10',
    },
    {
      type: 'Free Kicks',
      home: '25',
      away: '13',
    },
    {
      type: 'Corner Kicks',
      home: '7',
      away: '1',
    },
    {
      type: 'Throw-in',
      home: '19',
      away: '17',
    },
    {
      type: 'Goalkeeper Saves',
      home: '4',
      away: '6',
    },
    {
      type: 'Yellow Cards',
      home: '1',
      away: '3',
    },
    {
      type: 'Attacks',
      home: '90',
      away: '83',
    },
    {
      type: 'Dangerous Attacks',
      home: '65',
      away: '51',
    },
  ],
},
{
  match_id: '229698',
  country_id: '63',
  country_name: 'Indonesia',
  league_id: '244',
  league_name: 'Liga 1',
  match_date: '2019-07-03',
  match_status: 'Finished',
  match_time: '13:30',
  match_hometeam_id: '3971',
  match_hometeam_name: 'Kalteng Putra',
  match_hometeam_score: '0',
  match_awayteam_name: 'Pusamania Borneo',
  match_awayteam_id: '3940',
  match_awayteam_score: '1',
  match_hometeam_halftime_score: '0',
  match_awayteam_halftime_score: '1',
  match_hometeam_extra_score: '0',
  match_awayteam_extra_score: '1',
  match_hometeam_penalty_score: '',
  match_awayteam_penalty_score: '',
  match_hometeam_system: '4 - 3 - 3',
  match_awayteam_system: '4 - 3 - 3',
  match_live: '0',
  goalscorer: [
    {
      time: '45+3',
      home_scorer: '',
      score: '0 - 1',
      away_scorer: 'Baru L.',
    },
  ],
  cards: [
    {
      time: '26',
      home_fault: '',
      card: 'yellow card',
      away_fault: 'Rahman A.',
    },
    {
      time: '35',
      home_fault: 'Pali M.',
      card: 'yellow card',
      away_fault: '',
    },
    {
      time: '41',
      home_fault: 'Maran E.',
      card: 'yellow card',
      away_fault: '',
    },
    {
      time: '48',
      home_fault: '',
      card: 'yellow card',
      away_fault: 'Samma S.',
    },
    {
      time: '52',
      home_fault: '',
      card: 'yellow card',
      away_fault: '',
    },
    {
      time: '55',
      home_fault: 'Febrianto R.',
      card: 'yellow card',
      away_fault: '',
    },
    {
      time: '74',
      home_fault: '',
      card: 'yellow card',
      away_fault: 'Pasamba F.',
    },
    {
      time: '86',
      home_fault: 'Maulana D.',
      card: 'yellow card',
      away_fault: '',
    },
    {
      time: '88',
      home_fault: '',
      card: 'yellow card',
      away_fault: 'Kelvan A.',
    },
    {
      time: '90+3',
      home_fault: 'Nugroho A.',
      card: 'yellow card',
      away_fault: '',
    },
    {
      time: '90+3',
      home_fault: '',
      card: 'yellow card',
      away_fault: 'Lasut M.',
    },
  ],
  substitutions: {
    home: [
      {
        time: '45+4',
        substitution: 'Maran E. | Rumere M.',
      },
      {
        time: '57',
        substitution: 'Febrianto R. | Maulana D.',
      },
      {
        time: '77',
        substitution: 'Pali M. | Abanda Rahman A.',
      },
    ],
    away: [
      {
        time: '46',
        substitution: 'Wildansyah | Lammers J.',
      },
      {
        time: '76',
        substitution: 'Baru L. | Conti M.',
      },
      {
        time: '81',
        substitution: 'Samma S. | Lasut M.',
      },
    ],
  },
  lineup: {
    home: {
      starting_lineups: [
        {
          lineup_player: 'Apridianto D.',
          lineup_number: '7',
          lineup_position: '6',
        },
        {
          lineup_player: 'Bonfim',
          lineup_number: '33',
          lineup_position: '4',
        },
        {
          lineup_player: 'Febrianto R.',
          lineup_number: '12',
          lineup_position: '8',
        },
        {
          lineup_player: 'Hasbulla W.',
          lineup_number: '3',
          lineup_position: '2',
        },
        {
          lineup_player: 'John O. K.',
          lineup_number: '4',
          lineup_position: '3',
        },
        {
          lineup_player: 'Lestaluhu P.',
          lineup_number: '77',
          lineup_position: '11',
        },
        {
          lineup_player: 'Maran E.',
          lineup_number: '99',
          lineup_position: '9',
        },
        {
          lineup_player: 'Nugroho A.',
          lineup_number: '17',
          lineup_position: '10',
        },
        {
          lineup_player: 'Pali M.',
          lineup_number: '15',
          lineup_position: '5',
        },
        {
          lineup_player: 'Pratama D. (G)',
          lineup_number: '16',
          lineup_position: '1',
        },
        {
          lineup_player: 'Yoo Hyun-Goo (C)',
          lineup_number: '8',
          lineup_position: '7',
        },
      ],
      substitutes: [
        {
          lineup_player: 'Abanda Rahman A.',
          lineup_number: '21',
          lineup_position: '',
        },
        {
          lineup_player: 'Ariyanto D. (G)',
          lineup_number: '18',
          lineup_position: '',
        },
        {
          lineup_player: 'Azriel',
          lineup_number: '31',
          lineup_position: '',
        },
        {
          lineup_player: 'Maulana D.',
          lineup_number: '19',
          lineup_position: '',
        },
        {
          lineup_player: 'Riza B.',
          lineup_number: '22',
          lineup_position: '',
        },
        {
          lineup_player: 'Rumere M.',
          lineup_number: '14',
          lineup_position: '',
        },
        {
          lineup_player: 'Satria B.',
          lineup_number: '13',
          lineup_position: '',
        },
      ],
      coach: [
        {
          lineup_player: 'Gomes d. O. M.',
          lineup_number: '-1',
          lineup_position: '',
        },
      ],
      missing_players: [],
    },
    away: {
      starting_lineups: [
        {
          lineup_player: 'Azmi U.',
          lineup_number: '80',
          lineup_position: '11',
        },
        {
          lineup_player: 'Baru L. (C)',
          lineup_number: '12',
          lineup_position: '10',
        },
        {
          lineup_player: 'Guseynov J.',
          lineup_number: '19',
          lineup_position: '4',
        },
        {
          lineup_player: 'Kelvan A. (G)',
          lineup_number: '78',
          lineup_position: '1',
        },
        {
          lineup_player: 'Lastori R.',
          lineup_number: '11',
          lineup_position: '9',
        },
        {
          lineup_player: 'Pasamba F.',
          lineup_number: '25',
          lineup_position: '6',
        },
        {
          lineup_player: 'Rahman A.',
          lineup_number: '7',
          lineup_position: '5',
        },
        {
          lineup_player: 'Renan',
          lineup_number: '10',
          lineup_position: '7',
        },
        {
          lineup_player: 'Samma S.',
          lineup_number: '22',
          lineup_position: '8',
        },
        {
          lineup_player: 'Suruan M.',
          lineup_number: '87',
          lineup_position: '2',
        },
        {
          lineup_player: 'Wildansyah',
          lineup_number: '4',
          lineup_position: '3',
        },
      ],
      substitutes: [
        {
          lineup_player: 'Conti M.',
          lineup_number: '9',
          lineup_position: '',
        },
        {
          lineup_player: 'Diansyah N.',
          lineup_number: '44',
          lineup_position: '',
        },
        {
          lineup_player: 'Kurniawan I.',
          lineup_number: '48',
          lineup_position: '',
        },
        {
          lineup_player: 'Lammers J.',
          lineup_number: '3',
          lineup_position: '',
        },
        {
          lineup_player: 'Lasut M.',
          lineup_number: '15',
          lineup_position: '',
        },
        {
          lineup_player: 'Pandenuwu G. (G)',
          lineup_number: '31',
          lineup_position: '',
        },
        {
          lineup_player: 'Rahman F.',
          lineup_number: '37',
          lineup_position: '',
        },
      ],
      coach: [
        {
          lineup_player: 'Gomez M.',
          lineup_number: '-1',
          lineup_position: '',
        },
      ],
      missing_players: [],
    },
  },
  statistics: [
    {
      type: 'Ball Possession',
      home: '46%',
      away: '54%',
    },
    {
      type: 'Goal Attempts',
      home: '5',
      away: '8',
    },
    {
      type: 'Shots on Goal',
      home: '2',
      away: '5',
    },
    {
      type: 'Shots off Goal',
      home: '3',
      away: '3',
    },
    {
      type: 'Free Kicks',
      home: '27',
      away: '26',
    },
    {
      type: 'Corner Kicks',
      home: '1',
      away: '2',
    },
    {
      type: 'Throw-in',
      home: '18',
      away: '16',
    },
    {
      type: 'Goalkeeper Saves',
      home: '4',
      away: '2',
    },
    {
      type: 'Yellow Cards',
      home: '6',
      away: '5',
    },
    {
      type: 'Attacks',
      home: '90',
      away: '81',
    },
    {
      type: 'Dangerous Attacks',
      home: '48',
      away: '67',
    },
  ],
},
{
  match_id: '229891',
  country_id: '65',
  country_name: 'Iraq',
  league_id: '252',
  league_name: 'Super League',
  match_date: '2019-07-03',
  match_status: 'Finished',
  match_time: '16:00',
  match_hometeam_id: '4058',
  match_hometeam_name: 'Al Wasat',
  match_hometeam_score: '1',
  match_awayteam_name: 'Al Quwa Al Jawiya',
  match_awayteam_id: '4065',
  match_awayteam_score: '2',
  match_hometeam_halftime_score: '0',
  match_awayteam_halftime_score: '1',
  match_hometeam_extra_score: '0',
  match_awayteam_extra_score: '1',
  match_hometeam_penalty_score: '',
  match_awayteam_penalty_score: '',
  match_hometeam_system: '',
  match_awayteam_system: '',
  match_live: '0',
  goalscorer: [
    {
      time: '16',
      home_scorer: '',
      score: '0 - 1',
      away_scorer: 'Mohsin E.',
    },
    {
      time: '66',
      home_scorer: '',
      score: '0 - 2',
      away_scorer: 'Hashim A. Y.',
    },
    {
      time: '90+2',
      home_scorer: '',
      score: '1 - 2',
      away_scorer: '',
    },
  ],
  cards: [],
  substitutions: {
    home: [],
    away: [],
  },
  lineup: {
    home: {
      starting_lineups: [],
      substitutes: [],
      coach: [],
      missing_players: [],
    },
    away: {
      starting_lineups: [],
      substitutes: [],
      coach: [],
      missing_players: [],
    },
  },
  statistics: [],
},
{
  match_id: '229892',
  country_id: '65',
  country_name: 'Iraq',
  league_id: '252',
  league_name: 'Super League',
  match_date: '2019-07-03',
  match_status: 'Finished',
  match_time: '18:15',
  match_hometeam_id: '4057',
  match_hometeam_name: 'Al Bahri',
  match_hometeam_score: '2',
  match_awayteam_name: 'Al Hussein',
  match_awayteam_id: '4059',
  match_awayteam_score: '1',
  match_hometeam_halftime_score: '',
  match_awayteam_halftime_score: '',
  match_hometeam_extra_score: '',
  match_awayteam_extra_score: '',
  match_hometeam_penalty_score: '',
  match_awayteam_penalty_score: '',
  match_hometeam_system: '',
  match_awayteam_system: '',
  match_live: '0',
  goalscorer: [],
  cards: [],
  substitutions: {
    home: [],
    away: [],
  },
  lineup: {
    home: {
      starting_lineups: [],
      substitutes: [],
      coach: [],
      missing_players: [],
    },
    away: {
      starting_lineups: [],
      substitutes: [],
      coach: [],
      missing_players: [],
    },
  },
  statistics: [],
},
{
  match_id: '230354',
  country_id: '71',
  country_name: 'Japan',
  league_id: '277',
  league_name: 'Emperors Cup',
  match_date: '2019-07-03',
  match_status: 'Finished',
  match_time: '11:30',
  match_hometeam_id: '4369',
  match_hometeam_name: 'Hiroshima',
  match_hometeam_score: '4',
  match_awayteam_name: 'Okinawa SV',
  match_awayteam_id: '15045',
  match_awayteam_score: '0',
  match_hometeam_halftime_score: '0',
  match_awayteam_halftime_score: '0',
  match_hometeam_extra_score: '0',
  match_awayteam_extra_score: '0',
  match_hometeam_penalty_score: '',
  match_awayteam_penalty_score: '',
  match_hometeam_system: '',
  match_awayteam_system: '',
  match_live: '0',
  goalscorer: [
    {
      time: '47',
      home_scorer: 'Higashi S.',
      score: '1 - 0',
      away_scorer: '',
    },
    {
      time: '80',
      home_scorer: 'Matsumoto H.',
      score: '2 - 0',
      away_scorer: '',
    },
    {
      time: '83',
      home_scorer: 'Patric',
      score: '3 - 0',
      away_scorer: '',
    },
    {
      time: '90+1',
      home_scorer: 'Patric',
      score: '4 - 0',
      away_scorer: '',
    },
  ],
  cards: [],
  substitutions: {
    home: [],
    away: [],
  },
  lineup: {
    home: {
      starting_lineups: [],
      substitutes: [],
      coach: [],
      missing_players: [],
    },
    away: {
      starting_lineups: [],
      substitutes: [],
      coach: [],
      missing_players: [],
    },
  },
  statistics: [],
},
{
  match_id: '230355',
  country_id: '71',
  country_name: 'Japan',
  league_id: '277',
  league_name: 'Emperors Cup',
  match_date: '2019-07-03',
  match_status: 'After ET',
  match_time: '12:00',
  match_hometeam_id: '4396',
  match_hometeam_name: 'Avispa Fukuoka',
  match_hometeam_score: '2',
  match_awayteam_name: 'Kagoshima Utd',
  match_awayteam_id: '4426',
  match_awayteam_score: '1',
  match_hometeam_halftime_score: '1',
  match_awayteam_halftime_score: '1',
  match_hometeam_extra_score: '1',
  match_awayteam_extra_score: '1',
  match_hometeam_penalty_score: '',
  match_awayteam_penalty_score: '',
  match_hometeam_system: '',
  match_awayteam_system: '',
  match_live: '0',
  goalscorer: [
    {
      time: '35',
      home_scorer: '',
      score: '0 - 1',
      away_scorer: 'Nagahata Y.',
    },
    {
      time: '44',
      home_scorer: 'Maekawa T.',
      score: '1 - 1',
      away_scorer: '',
    },
    {
      time: '102',
      home_scorer: 'Kido K.',
      score: '2 - 1',
      away_scorer: '',
    },
  ],
  cards: [],
  substitutions: {
    home: [],
    away: [],
  },
  lineup: {
    home: {
      starting_lineups: [],
      substitutes: [],
      coach: [],
      missing_players: [],
    },
    away: {
      starting_lineups: [],
      substitutes: [],
      coach: [],
      missing_players: [],
    },
  },
  statistics: [],
},
{
  match_id: '230356',
  country_id: '71',
  country_name: 'Japan',
  league_id: '277',
  league_name: 'Emperors Cup',
  match_date: '2019-07-03',
  match_status: 'Finished',
  match_time: '12:00',
  match_hometeam_id: '4400',
  match_hometeam_name: 'Chiba',
  match_hometeam_score: '0',
  match_awayteam_name: 'Okayama',
  match_awayteam_id: '4390',
  match_awayteam_score: '3',
  match_hometeam_halftime_score: '0',
  match_awayteam_halftime_score: '1',
  match_hometeam_extra_score: '0',
  match_awayteam_extra_score: '1',
  match_hometeam_penalty_score: '',
  match_awayteam_penalty_score: '',
  match_hometeam_system: '',
  match_awayteam_system: '',
  match_live: '0',
  goalscorer: [
    {
      time: '45+2',
      home_scorer: '',
      score: '0 - 1',
      away_scorer: 'Masuda S.',
    },
    {
      time: '70',
      home_scorer: '',
      score: '0 - 2',
      away_scorer: 'Fukumoto T.',
    },
    {
      time: '90+5',
      home_scorer: '',
      score: '0 - 3',
      away_scorer: '',
    },
  ],
  cards: [],
  substitutions: {
    home: [],
    away: [],
  },
  lineup: {
    home: {
      starting_lineups: [],
      substitutes: [],
      coach: [],
      missing_players: [],
    },
    away: {
      starting_lineups: [],
      substitutes: [],
      coach: [],
      missing_players: [],
    },
  },
  statistics: [],
},
{
  match_id: '230357',
  country_id: '71',
  country_name: 'Japan',
  league_id: '277',
  league_name: 'Emperors Cup',
  match_date: '2019-07-03',
  match_status: 'Finished',
  match_time: '12:00',
  match_hometeam_id: '4363',
  match_hometeam_name: 'FC Tokyo',
  match_hometeam_score: '1',
  match_awayteam_name: 'Toin University',
  match_awayteam_id: '15046',
  match_awayteam_score: '0',
  match_hometeam_halftime_score: '0',
  match_awayteam_halftime_score: '0',
  match_hometeam_extra_score: '0',
  match_awayteam_extra_score: '0',
  match_hometeam_penalty_score: '',
  match_awayteam_penalty_score: '',
  match_hometeam_system: '',
  match_awayteam_system: '',
  match_live: '0',
  goalscorer: [
    {
      time: '50',
      home_scorer: 'Uchida T.',
      score: '1 - 0',
      away_scorer: '',
    },
  ],
  cards: [],
  substitutions: {
    home: [],
    away: [],
  },
  lineup: {
    home: {
      starting_lineups: [],
      substitutes: [],
      coach: [],
      missing_players: [],
    },
    away: {
      starting_lineups: [],
      substitutes: [],
      coach: [],
      missing_players: [],
    },
  },
  statistics: [],
},
{
  match_id: '230358',
  country_id: '71',
  country_name: 'Japan',
  league_id: '277',
  league_name: 'Emperors Cup',
  match_date: '2019-07-03',
  match_status: 'Finished',
  match_time: '12:00',
  match_hometeam_id: '4367',
  match_hometeam_name: 'G-Osaka',
  match_hometeam_score: '7',
  match_awayteam_name: 'Kamatamare',
  match_awayteam_id: '4386',
  match_awayteam_score: '1',
  match_hometeam_halftime_score: '3',
  match_awayteam_halftime_score: '1',
  match_hometeam_extra_score: '3',
  match_awayteam_extra_score: '1',
  match_hometeam_penalty_score: '',
  match_awayteam_penalty_score: '',
  match_hometeam_system: '',
  match_awayteam_system: '',
  match_live: '0',
  goalscorer: [
    {
      time: '10',
      home_scorer: 'Nakamura K.',
      score: '1 - 0',
      away_scorer: '',
    },
    {
      time: '14',
      home_scorer: 'Nakamura K.',
      score: '2 - 0',
      away_scorer: '',
    },
    {
      time: '24',
      home_scorer: 'Tono K.',
      score: '3 - 0',
      away_scorer: '',
    },
    {
      time: '40',
      home_scorer: '',
      score: '3 - 1',
      away_scorer: 'Arabori K.',
    },
    {
      time: '75',
      home_scorer: 'Takagi A.',
      score: '4 - 1',
      away_scorer: '',
    },
    {
      time: '79',
      home_scorer: 'Nakamura K.',
      score: '5 - 1',
      away_scorer: '',
    },
    {
      time: '82',
      home_scorer: 'Takagi A.',
      score: '6 - 1',
      away_scorer: '',
    },
    {
      time: '90+4',
      home_scorer: '',
      score: '7 - 1',
      away_scorer: '',
    },
  ],
  cards: [],
  substitutions: {
    home: [],
    away: [],
  },
  lineup: {
    home: {
      starting_lineups: [],
      substitutes: [],
      coach: [],
      missing_players: [],
    },
    away: {
      starting_lineups: [],
      substitutes: [],
      coach: [],
      missing_players: [],
    },
  },
  statistics: [],
},
{
  match_id: '230359',
  country_id: '71',
  country_name: 'Japan',
  league_id: '277',
  league_name: 'Emperors Cup',
  match_date: '2019-07-03',
  match_status: 'Finished',
  match_time: '12:00',
  match_hometeam_id: '4377',
  match_hometeam_name: 'Iwata',
  match_hometeam_score: '5',
  match_awayteam_name: 'Honda Lock',
  match_awayteam_id: '15047',
  match_awayteam_score: '2',
  match_hometeam_halftime_score: '1',
  match_awayteam_halftime_score: '1',
  match_hometeam_extra_score: '1',
  match_awayteam_extra_score: '1',
  match_hometeam_penalty_score: '',
  match_awayteam_penalty_score: '',
  match_hometeam_system: '',
  match_awayteam_system: '',
  match_live: '0',
  goalscorer: [
    {
      time: '27',
      home_scorer: 'Hitoto N.',
      score: '1 - 0',
      away_scorer: '',
    },
    {
      time: '39',
      home_scorer: '',
      score: '1 - 1',
      away_scorer: 'Hayato T.',
    },
    {
      time: '54',
      home_scorer: 'Nakayama M.',
      score: '2 - 1',
      away_scorer: '',
    },
    {
      time: '59',
      home_scorer: '',
      score: '2 - 2',
      away_scorer: 'Ando',
    },
    {
      time: '61',
      home_scorer: 'Moriya K.',
      score: '3 - 2',
      away_scorer: '',
    },
    {
      time: '64',
      home_scorer: 'Morishita S.',
      score: '4 - 2',
      away_scorer: '',
    },
    {
      time: '90+4',
      home_scorer: '',
      score: '5 - 2',
      away_scorer: '',
    },
  ],
  cards: [],
  substitutions: {
    home: [],
    away: [],
  },
  lineup: {
    home: {
      starting_lineups: [],
      substitutes: [],
      coach: [],
      missing_players: [],
    },
    away: {
      starting_lineups: [],
      substitutes: [],
      coach: [],
      missing_players: [],
    },
  },
  statistics: [],
},
{
  match_id: '230360',
  country_id: '71',
  country_name: 'Japan',
  league_id: '277',
  league_name: 'Emperors Cup',
  match_date: '2019-07-03',
  match_status: 'Finished',
  match_time: '12:00',
  match_hometeam_id: '4388',
  match_hometeam_name: 'Kanazawa',
  match_hometeam_score: '1',
  match_awayteam_name: 'Albirex Niigata',
  match_awayteam_id: '4379',
  match_awayteam_score: '0',
  match_hometeam_halftime_score: '0',
  match_awayteam_halftime_score: '0',
  match_hometeam_extra_score: '0',
  match_awayteam_extra_score: '0',
  match_hometeam_penalty_score: '',
  match_awayteam_penalty_score: '',
  match_hometeam_system: '',
  match_awayteam_system: '',
  match_live: '0',
  goalscorer: [
    {
      time: '59',
      home_scorer: 'Sugiura K.',
      score: '1 - 0',
      away_scorer: '',
    },
  ],
  cards: [],
  substitutions: {
    home: [],
    away: [],
  },
  lineup: {
    home: {
      starting_lineups: [],
      substitutes: [],
      coach: [],
      missing_players: [],
    },
    away: {
      starting_lineups: [],
      substitutes: [],
      coach: [],
      missing_players: [],
    },
  },
  statistics: [],
},
{
  match_id: '230361',
  country_id: '71',
  country_name: 'Japan',
  league_id: '277',
  league_name: 'Emperors Cup',
  match_date: '2019-07-03',
  match_status: 'Finished',
  match_time: '12:00',
  match_hometeam_id: '4376',
  match_hometeam_name: 'Kashima',
  match_hometeam_score: '3',
  match_awayteam_name: 'Hokuriku',
  match_awayteam_id: '15048',
  match_awayteam_score: '1',
  match_hometeam_halftime_score: '3',
  match_awayteam_halftime_score: '0',
  match_hometeam_extra_score: '3',
  match_awayteam_extra_score: '0',
  match_hometeam_penalty_score: '',
  match_awayteam_penalty_score: '',
  match_hometeam_system: '',
  match_awayteam_system: '',
  match_live: '0',
  goalscorer: [
    {
      time: '4',
      home_scorer: 'Serginho',
      score: '1 - 0',
      away_scorer: '',
    },
    {
      time: '10',
      home_scorer: 'Yamaguchi K.',
      score: '2 - 0',
      away_scorer: '',
    },
    {
      time: '14',
      home_scorer: 'Kanamori T.',
      score: '3 - 0',
      away_scorer: '',
    },
    {
      time: '71',
      home_scorer: '',
      score: '3 - 1',
      away_scorer: 'Takahashi H.',
    },
  ],
  cards: [],
  substitutions: {
    home: [],
    away: [],
  },
  lineup: {
    home: {
      starting_lineups: [],
      substitutes: [],
      coach: [],
      missing_players: [],
    },
    away: {
      starting_lineups: [],
      substitutes: [],
      coach: [],
      missing_players: [],
    },
  },
  statistics: [],
},
{
  match_id: '230362',
  country_id: '71',
  country_name: 'Japan',
  league_id: '277',
  league_name: 'Emperors Cup',
  match_date: '2019-07-03',
  match_status: 'Finished',
  match_time: '12:00',
  match_hometeam_id: '4371',
  match_hometeam_name: 'Kashiwa',
  match_hometeam_score: '4',
  match_awayteam_name: 'Grulla Morioka',
  match_awayteam_id: '4423',
  match_awayteam_score: '0',
  match_hometeam_halftime_score: '1',
  match_awayteam_halftime_score: '0',
  match_hometeam_extra_score: '1',
  match_awayteam_extra_score: '0',
  match_hometeam_penalty_score: '',
  match_awayteam_penalty_score: '',
  match_hometeam_system: '',
  match_awayteam_system: '',
  match_live: '0',
  goalscorer: [
    {
      time: '24',
      home_scorer: 'Tezuka K.',
      score: '1 - 0',
      away_scorer: '',
    },
    {
      time: '66',
      home_scorer: 'Esaka A.',
      score: '2 - 0',
      away_scorer: '',
    },
    {
      time: '75',
      home_scorer: 'Esaka A.',
      score: '3 - 0',
      away_scorer: '',
    },
    {
      time: '86',
      home_scorer: '',
      score: '4 - 0',
      away_scorer: '',
    },
  ],
  cards: [],
  substitutions: {
    home: [],
    away: [],
  },
  lineup: {
    home: {
      starting_lineups: [],
      substitutes: [],
      coach: [],
      missing_players: [],
    },
    away: {
      starting_lineups: [],
      substitutes: [],
      coach: [],
      missing_players: [],
    },
  },
  statistics: [],
},
{
  match_id: '230363',
  country_id: '71',
  country_name: 'Japan',
  league_id: '277',
  league_name: 'Emperors Cup',
  match_date: '2019-07-03',
  match_status: 'Finished',
  match_time: '12:00',
  match_hometeam_id: '4372',
  match_hometeam_name: 'Kawasaki Frontale',
  match_hometeam_score: '1',
  match_awayteam_name: 'Meiji Univ.',
  match_awayteam_id: '15049',
  match_awayteam_score: '0',
  match_hometeam_halftime_score: '1',
  match_awayteam_halftime_score: '0',
  match_hometeam_extra_score: '1',
  match_awayteam_extra_score: '0',
  match_hometeam_penalty_score: '',
  match_awayteam_penalty_score: '',
  match_hometeam_system: '',
  match_awayteam_system: '',
  match_live: '0',
  goalscorer: [
    {
      time: '15',
      home_scorer: 'Chinen K.',
      score: '1 - 0',
      away_scorer: '',
    },
  ],
  cards: [],
  substitutions: {
    home: [],
    away: [],
  },
  lineup: {
    home: {
      starting_lineups: [],
      substitutes: [],
      coach: [],
      missing_players: [],
    },
    away: {
      starting_lineups: [],
      substitutes: [],
      coach: [],
      missing_players: [],
    },
  },
  statistics: [],
},
{
  match_id: '230364',
  country_id: '71',
  country_name: 'Japan',
  league_id: '277',
  league_name: 'Emperors Cup',
  match_date: '2019-07-03',
  match_status: 'Finished',
  match_time: '12:00',
  match_hometeam_id: '4374',
  match_hometeam_name: 'Kobe',
  match_hometeam_score: '4',
  match_awayteam_name: 'Giravanz Kitakyushu',
  match_awayteam_id: '4421',
  match_awayteam_score: '0',
  match_hometeam_halftime_score: '1',
  match_awayteam_halftime_score: '0',
  match_hometeam_extra_score: '1',
  match_awayteam_extra_score: '0',
  match_hometeam_penalty_score: '',
  match_awayteam_penalty_score: '',
  match_hometeam_system: '',
  match_awayteam_system: '',
  match_live: '0',
  goalscorer: [
    {
      time: '44',
      home_scorer: 'Yasui T.',
      score: '1 - 0',
      away_scorer: '',
    },
    {
      time: '56',
      home_scorer: 'Ogawa K.',
      score: '2 - 0',
      away_scorer: '',
    },
    {
      time: '64',
      home_scorer: 'Tanaka J.',
      score: '3 - 0',
      away_scorer: '',
    },
    {
      time: '80',
      home_scorer: 'Samper S.',
      score: '4 - 0',
      away_scorer: '',
    },
  ],
  cards: [],
  substitutions: {
    home: [],
    away: [],
  },
  lineup: {
    home: {
      starting_lineups: [],
      substitutes: [],
      coach: [],
      missing_players: [],
    },
    away: {
      starting_lineups: [],
      substitutes: [],
      coach: [],
      missing_players: [],
    },
  },
  statistics: [],
},
{
  match_id: '230365',
  country_id: '71',
  country_name: 'Japan',
  league_id: '277',
  league_name: 'Emperors Cup',
  match_date: '2019-07-03',
  match_status: 'After Pen.',
  match_time: '12:00',
  match_hometeam_id: '4373',
  match_hometeam_name: 'Kofu',
  match_hometeam_score: '3',
  match_awayteam_name: 'Gifu',
  match_awayteam_id: '4392',
  match_awayteam_score: '2',
  match_hometeam_halftime_score: '1',
  match_awayteam_halftime_score: '0',
  match_hometeam_extra_score: '1',
  match_awayteam_extra_score: '0',
  match_hometeam_penalty_score: '4',
  match_awayteam_penalty_score: '2',
  match_hometeam_system: '',
  match_awayteam_system: '',
  match_live: '0',
  goalscorer: [
    {
      time: '6',
      home_scorer: 'Ota S.',
      score: '1 - 0',
      away_scorer: '',
    },
    {
      time: '51',
      home_scorer: '',
      score: '1 - 1',
      away_scorer: 'Fujitani T.',
    },
    {
      time: '67',
      home_scorer: 'Koyanagi T.',
      score: '2 - 1',
      away_scorer: '',
    },
    {
      time: '90+3',
      home_scorer: '',
      score: '2 - 2',
      away_scorer: 'Fujitani T.',
    },
    {
      time: '2',
      home_scorer: '',
      score: '2 - 3',
      away_scorer: '',
    },
    {
      time: '1',
      home_scorer: '',
      score: '3 - 3',
      away_scorer: '',
    },
    {
      time: '2',
      home_scorer: '',
      score: '4 - 3',
      away_scorer: '',
    },
    {
      time: '3',
      home_scorer: '',
      score: '5 - 3',
      away_scorer: '',
    },
    {
      time: '4',
      home_scorer: '',
      score: '5 - 4',
      away_scorer: '',
    },
    {
      time: '4',
      home_scorer: '',
      score: '6 - 4',
      away_scorer: '',
    },
  ],
  cards: [],
  substitutions: {
    home: [],
    away: [],
  },
  lineup: {
    home: {
      starting_lineups: [],
      substitutes: [],
      coach: [],
      missing_players: [],
    },
    away: {
      starting_lineups: [],
      substitutes: [],
      coach: [],
      missing_players: [],
    },
  },
  statistics: [],
},
{
  match_id: '230366',
  country_id: '71',
  country_name: 'Japan',
  league_id: '277',
  league_name: 'Emperors Cup',
  match_date: '2019-07-03',
  match_status: 'Finished',
  match_time: '12:00',
  match_hometeam_id: '4385',
  match_hometeam_name: 'Machida',
  match_hometeam_score: '0',
  match_awayteam_name: 'Toyama',
  match_awayteam_id: '4416',
  match_awayteam_score: '1',
  match_hometeam_halftime_score: '0',
  match_awayteam_halftime_score: '1',
  match_hometeam_extra_score: '0',
  match_awayteam_extra_score: '1',
  match_hometeam_penalty_score: '',
  match_awayteam_penalty_score: '',
  match_hometeam_system: '',
  match_awayteam_system: '',
  match_live: '0',
  goalscorer: [
    {
      time: '22',
      home_scorer: '',
      score: '0 - 1',
      away_scorer: 'Sasaki K.',
    },
  ],
  cards: [],
  substitutions: {
    home: [],
    away: [],
  },
  lineup: {
    home: {
      starting_lineups: [],
      substitutes: [],
      coach: [],
      missing_players: [],
    },
    away: {
      starting_lineups: [],
      substitutes: [],
      coach: [],
      missing_players: [],
    },
  },
  statistics: [],
},
{
  match_id: '230367',
  country_id: '71',
  country_name: 'Japan',
  league_id: '277',
  league_name: 'Emperors Cup',
  match_date: '2019-07-03',
  match_status: 'Finished',
  match_time: '12:00',
  match_hometeam_id: '4402',
  match_hometeam_name: 'Mito',
  match_hometeam_score: '1',
  match_awayteam_name: 'Kyoto',
  match_awayteam_id: '4393',
  match_awayteam_score: '0',
  match_hometeam_halftime_score: '0',
  match_awayteam_halftime_score: '0',
  match_hometeam_extra_score: '0',
  match_awayteam_extra_score: '0',
  match_hometeam_penalty_score: '',
  match_awayteam_penalty_score: '',
  match_hometeam_system: '',
  match_awayteam_system: '',
  match_live: '0',
  goalscorer: [
    {
      time: '90+2',
      home_scorer: '',
      score: '1 - 0',
      away_scorer: '',
    },
  ],
  cards: [],
  substitutions: {
    home: [],
    away: [],
  },
  lineup: {
    home: {
      starting_lineups: [],
      substitutes: [],
      coach: [],
      missing_players: [],
    },
    away: {
      starting_lineups: [],
      substitutes: [],
      coach: [],
      missing_players: [],
    },
  },
  statistics: [],
},
{
  match_id: '230368',
  country_id: '71',
  country_name: 'Japan',
  league_id: '277',
  league_name: 'Emperors Cup',
  match_date: '2019-07-03',
  match_status: 'Finished',
  match_time: '12:00',
  match_hometeam_id: '4381',
  match_hometeam_name: 'Montedio Yamagata',
  match_hometeam_score: '1',
  match_awayteam_name: 'Tochigi',
  match_awayteam_id: '10436',
  match_awayteam_score: '2',
  match_hometeam_halftime_score: '1',
  match_awayteam_halftime_score: '1',
  match_hometeam_extra_score: '1',
  match_awayteam_extra_score: '1',
  match_hometeam_penalty_score: '',
  match_awayteam_penalty_score: '',
  match_hometeam_system: '',
  match_awayteam_system: '',
  match_live: '0',
  goalscorer: [
    {
      time: '2',
      home_scorer: '',
      score: '0 - 1',
      away_scorer: 'Sakaki S.',
    },
    {
      time: '39',
      home_scorer: 'Kitagawa S.',
      score: '1 - 1',
      away_scorer: '',
    },
    {
      time: '78',
      home_scorer: '',
      score: '1 - 2',
      away_scorer: 'Hiraoka T.',
    },
  ],
  cards: [],
  substitutions: {
    home: [],
    away: [],
  },
  lineup: {
    home: {
      starting_lineups: [],
      substitutes: [],
      coach: [],
      missing_players: [],
    },
    away: {
      starting_lineups: [],
      substitutes: [],
      coach: [],
      missing_players: [],
    },
  },
  statistics: [],
},
{
  match_id: '230369',
  country_id: '71',
  country_name: 'Japan',
  league_id: '277',
  league_name: 'Emperors Cup',
  match_date: '2019-07-03',
  match_status: 'Finished',
  match_time: '12:00',
  match_hometeam_id: '4383',
  match_hometeam_name: 'Nagoya',
  match_hometeam_score: '0',
  match_awayteam_name: 'Kanoya Univ.',
  match_awayteam_id: '15050',
  match_awayteam_score: '3',
  match_hometeam_halftime_score: '0',
  match_awayteam_halftime_score: '0',
  match_hometeam_extra_score: '0',
  match_awayteam_extra_score: '0',
  match_hometeam_penalty_score: '',
  match_awayteam_penalty_score: '',
  match_hometeam_system: '',
  match_awayteam_system: '',
  match_live: '0',
  goalscorer: [
    {
      time: '46',
      home_scorer: '',
      score: '0 - 1',
      away_scorer: 'Tatsuo I.',
    },
    {
      time: '67',
      home_scorer: '',
      score: '0 - 2',
      away_scorer: 'Nemoto',
    },
    {
      time: '81',
      home_scorer: '',
      score: '0 - 3',
      away_scorer: 'Fujimoto K.',
    },
  ],
  cards: [],
  substitutions: {
    home: [],
    away: [],
  },
  lineup: {
    home: {
      starting_lineups: [],
      substitutes: [],
      coach: [],
      missing_players: [],
    },
    away: {
      starting_lineups: [],
      substitutes: [],
      coach: [],
      missing_players: [],
    },
  },
  statistics: [],
},
{
  match_id: '230370',
  country_id: '71',
  country_name: 'Japan',
  league_id: '277',
  league_name: 'Emperors Cup',
  match_date: '2019-07-03',
  match_status: 'Finished',
  match_time: '12:00',
  match_hometeam_id: '4399',
  match_hometeam_name: 'Oita',
  match_hometeam_score: '4',
  match_awayteam_name: 'Gainare Tottori',
  match_awayteam_id: '11005',
  match_awayteam_score: '1',
  match_hometeam_halftime_score: '2',
  match_awayteam_halftime_score: '0',
  match_hometeam_extra_score: '2',
  match_awayteam_extra_score: '0',
  match_hometeam_penalty_score: '',
  match_awayteam_penalty_score: '',
  match_hometeam_system: '',
  match_awayteam_system: '',
  match_live: '0',
  goalscorer: [
    {
      time: '30',
      home_scorer: 'Mitsuhira K.',
      score: '1 - 0',
      away_scorer: '',
    },
    {
      time: '37',
      home_scorer: 'Tone R.',
      score: '2 - 0',
      away_scorer: '',
    },
    {
      time: '69',
      home_scorer: 'Mitsuhira K.',
      score: '3 - 0',
      away_scorer: '',
    },
    {
      time: '82',
      home_scorer: '',
      score: '3 - 1',
      away_scorer: 'Gabriel Vitor',
    },
    {
      time: '90+3',
      home_scorer: 'Goto Y.',
      score: '4 - 1',
      away_scorer: '',
    },
  ],
  cards: [],
  substitutions: {
    home: [],
    away: [],
  },
  lineup: {
    home: {
      starting_lineups: [],
      substitutes: [],
      coach: [],
      missing_players: [],
    },
    away: {
      starting_lineups: [],
      substitutes: [],
      coach: [],
      missing_players: [],
    },
  },
  statistics: [],
},
{
  match_id: '230371',
  country_id: '71',
  country_name: 'Japan',
  league_id: '277',
  league_name: 'Emperors Cup',
  match_date: '2019-07-03',
  match_status: 'After ET',
  match_time: '12:00',
  match_hometeam_id: '4366',
  match_hometeam_name: 'Omiya Ardija',
  match_hometeam_score: '2',
  match_awayteam_name: 'Kusatsu',
  match_awayteam_id: '4384',
  match_awayteam_score: '1',
  match_hometeam_halftime_score: '1',
  match_awayteam_halftime_score: '0',
  match_hometeam_extra_score: '1',
  match_awayteam_extra_score: '0',
  match_hometeam_penalty_score: '',
  match_awayteam_penalty_score: '',
  match_hometeam_system: '',
  match_awayteam_system: '',
  match_live: '0',
  goalscorer: [
    {
      time: '10',
      home_scorer: 'Motoki O.',
      score: '1 - 0',
      away_scorer: '',
    },
    {
      time: '71',
      home_scorer: '',
      score: '1 - 1',
      away_scorer: 'Fukuda',
    },
    {
      time: '120+6',
      home_scorer: '',
      score: '2 - 1',
      away_scorer: '',
    },
  ],
  cards: [],
  substitutions: {
    home: [],
    away: [],
  },
  lineup: {
    home: {
      starting_lineups: [],
      substitutes: [],
      coach: [],
      missing_players: [],
    },
    away: {
      starting_lineups: [],
      substitutes: [],
      coach: [],
      missing_players: [],
    },
  },
  statistics: [],
},
{
  match_id: '230372',
  country_id: '71',
  country_name: 'Japan',
  league_id: '277',
  league_name: 'Emperors Cup',
  match_date: '2019-07-03',
  match_status: 'Finished',
  match_time: '12:00',
  match_hometeam_id: '4387',
  match_hometeam_name: 'Renofa Yamaguchi',
  match_hometeam_score: '2',
  match_awayteam_name: 'Ryukyu',
  match_awayteam_id: '4427',
  match_awayteam_score: '1',
  match_hometeam_halftime_score: '1',
  match_awayteam_halftime_score: '1',
  match_hometeam_extra_score: '1',
  match_awayteam_extra_score: '1',
  match_hometeam_penalty_score: '',
  match_awayteam_penalty_score: '',
  match_hometeam_system: '',
  match_awayteam_system: '',
  match_live: '0',
  goalscorer: [
    {
      time: '15',
      home_scorer: '',
      score: '0 - 1',
      away_scorer: 'Kamimon T.',
    },
    {
      time: '25',
      home_scorer: 'Kudo S.',
      score: '1 - 1',
      away_scorer: '',
    },
    {
      time: '73',
      home_scorer: 'Yamashita K.',
      score: '2 - 1',
      away_scorer: '',
    },
  ],
  cards: [],
  substitutions: {
    home: [],
    away: [],
  },
  lineup: {
    home: {
      starting_lineups: [],
      substitutes: [],
      coach: [],
      missing_players: [],
    },
    away: {
      starting_lineups: [],
      substitutes: [],
      coach: [],
      missing_players: [],
    },
  },
  statistics: [],
},
{
  match_id: '230373',
  country_id: '71',
  country_name: 'Japan',
  league_id: '277',
  league_name: 'Emperors Cup',
  match_date: '2019-07-03',
  match_status: 'After Pen.',
  match_time: '12:00',
  match_hometeam_id: '4380',
  match_hometeam_name: 'Sagan Tosu',
  match_hometeam_score: '2',
  match_awayteam_name: 'Kumamoto',
  match_awayteam_id: '4397',
  match_awayteam_score: '1',
  match_hometeam_halftime_score: '0',
  match_awayteam_halftime_score: '0',
  match_hometeam_extra_score: '0',
  match_awayteam_extra_score: '0',
  match_hometeam_penalty_score: '4',
  match_awayteam_penalty_score: '3',
  match_hometeam_system: '',
  match_awayteam_system: '',
  match_live: '0',
  goalscorer: [
    {
      time: '62',
      home_scorer: 'Ibarbo V.',
      score: '1 - 0',
      away_scorer: '',
    },
    {
      time: '65',
      home_scorer: '',
      score: '1 - 1',
      away_scorer: 'Ueda R.',
    },
  ],
  cards: [],
  substitutions: {
    home: [],
    away: [],
  },
  lineup: {
    home: {
      starting_lineups: [],
      substitutes: [],
      coach: [],
      missing_players: [],
    },
    away: {
      starting_lineups: [],
      substitutes: [],
      coach: [],
      missing_players: [],
    },
  },
  statistics: [],
},
{
  match_id: '230374',
  country_id: '71',
  country_name: 'Japan',
  league_id: '277',
  league_name: 'Emperors Cup',
  match_date: '2019-07-03',
  match_status: 'Finished',
  match_time: '12:00',
  match_hometeam_id: '4375',
  match_hometeam_name: 'Sapporo',
  match_hometeam_score: '2',
  match_awayteam_name: 'Honda FC',
  match_awayteam_id: '4412',
  match_awayteam_score: '4',
  match_hometeam_halftime_score: '1',
  match_awayteam_halftime_score: '2',
  match_hometeam_extra_score: '1',
  match_awayteam_extra_score: '2',
  match_hometeam_penalty_score: '',
  match_awayteam_penalty_score: '',
  match_hometeam_system: '',
  match_awayteam_system: '',
  match_live: '0',
  goalscorer: [
    {
      time: '13',
      home_scorer: '',
      score: '0 - 1',
      away_scorer: 'Tono D.',
    },
    {
      time: '31',
      home_scorer: '',
      score: '0 - 2',
      away_scorer: 'Tono D.',
    },
    {
      time: '33',
      home_scorer: 'Nakamura T.',
      score: '1 - 2',
      away_scorer: '',
    },
    {
      time: '55',
      home_scorer: 'Fujimura R.',
      score: '2 - 2',
      away_scorer: '',
    },
    {
      time: '65',
      home_scorer: '',
      score: '2 - 3',
      away_scorer: 'Furuhashi T.',
    },
    {
      time: '86',
      home_scorer: '',
      score: '2 - 4',
      away_scorer: 'Daiki I.',
    },
  ],
  cards: [],
  substitutions: {
    home: [],
    away: [],
  },
  lineup: {
    home: {
      starting_lineups: [],
      substitutes: [],
      coach: [],
      missing_players: [],
    },
    away: {
      starting_lineups: [],
      substitutes: [],
      coach: [],
      missing_players: [],
    },
  },
  statistics: [],
},
{
  match_id: '230375',
  country_id: '71',
  country_name: 'Japan',
  league_id: '277',
  league_name: 'Emperors Cup',
  match_date: '2019-07-03',
  match_status: 'Finished',
  match_time: '12:00',
  match_hometeam_id: '4364',
  match_hometeam_name: 'Shimizu',
  match_hometeam_score: '1',
  match_awayteam_name: 'Nagano',
  match_awayteam_id: '4403',
  match_awayteam_score: '0',
  match_hometeam_halftime_score: '0',
  match_awayteam_halftime_score: '0',
  match_hometeam_extra_score: '0',
  match_awayteam_extra_score: '0',
  match_hometeam_penalty_score: '',
  match_awayteam_penalty_score: '',
  match_hometeam_system: '',
  match_awayteam_system: '',
  match_live: '0',
  goalscorer: [
    {
      time: '90+2',
      home_scorer: '',
      score: '1 - 0',
      away_scorer: '',
    },
  ],
  cards: [],
  substitutions: {
    home: [],
    away: [],
  },
  lineup: {
    home: {
      starting_lineups: [],
      substitutes: [],
      coach: [],
      missing_players: [],
    },
    away: {
      starting_lineups: [],
      substitutes: [],
      coach: [],
      missing_players: [],
    },
  },
  statistics: [],
},
{
  match_id: '230376',
  country_id: '71',
  country_name: 'Japan',
  league_id: '277',
  league_name: 'Emperors Cup',
  match_date: '2019-07-03',
  match_status: 'Finished',
  match_time: '12:00',
  match_hometeam_id: '4389',
  match_hometeam_name: 'Shonan',
  match_hometeam_score: '0',
  match_awayteam_name: 'Veertien Mie',
  match_awayteam_id: '15051',
  match_awayteam_score: '4',
  match_hometeam_halftime_score: '0',
  match_awayteam_halftime_score: '1',
  match_hometeam_extra_score: '0',
  match_awayteam_extra_score: '1',
  match_hometeam_penalty_score: '',
  match_awayteam_penalty_score: '',
  match_hometeam_system: '',
  match_awayteam_system: '',
  match_live: '0',
  goalscorer: [
    {
      time: '22',
      home_scorer: '',
      score: '0 - 1',
      away_scorer: 'Sakai S.',
    },
    {
      time: '50',
      home_scorer: '',
      score: '0 - 2',
      away_scorer: 'Sakai S.',
    },
    {
      time: '58',
      home_scorer: '',
      score: '0 - 3',
      away_scorer: 'Sakai S.',
    },
    {
      time: '71',
      home_scorer: '',
      score: '0 - 4',
      away_scorer: 'Kitano J.',
    },
  ],
  cards: [],
  substitutions: {
    home: [],
    away: [],
  },
  lineup: {
    home: {
      starting_lineups: [],
      substitutes: [],
      coach: [],
      missing_players: [],
    },
    away: {
      starting_lineups: [],
      substitutes: [],
      coach: [],
      missing_players: [],
    },
  },
  statistics: [],
},
{
  match_id: '230377',
  country_id: '71',
  country_name: 'Japan',
  league_id: '277',
  league_name: 'Emperors Cup',
  match_date: '2019-07-03',
  match_status: 'After Pen.',
  match_time: '12:00',
  match_hometeam_id: '4401',
  match_hometeam_name: 'Tokushima',
  match_hometeam_score: '1',
  match_awayteam_name: 'Ehime',
  match_awayteam_id: '4382',
  match_awayteam_score: '0',
  match_hometeam_halftime_score: '0',
  match_awayteam_halftime_score: '0',
  match_hometeam_extra_score: '0',
  match_awayteam_extra_score: '0',
  match_hometeam_penalty_score: '5',
  match_awayteam_penalty_score: '3',
  match_hometeam_system: '',
  match_awayteam_system: '',
  match_live: '0',
  goalscorer: [
    {
      time: '1',
      home_scorer: '',
      score: '1 - 0',
      away_scorer: '',
    },
    {
      time: '1',
      home_scorer: '',
      score: '1 - 1',
      away_scorer: '',
    },
    {
      time: '2',
      home_scorer: '',
      score: '2 - 1',
      away_scorer: '',
    },
    {
      time: '2',
      home_scorer: '',
      score: '2 - 2',
      away_scorer: '',
    },
    {
      time: '3',
      home_scorer: '',
      score: '3 - 2',
      away_scorer: '',
    },
    {
      time: '4',
      home_scorer: '',
      score: '4 - 2',
      away_scorer: '',
    },
    {
      time: '4',
      home_scorer: '',
      score: '4 - 3',
      away_scorer: '',
    },
    {
      time: '5',
      home_scorer: '',
      score: '5 - 3',
      away_scorer: '',
    },
  ],
  cards: [],
  substitutions: {
    home: [],
    away: [],
  },
  lineup: {
    home: {
      starting_lineups: [],
      substitutes: [],
      coach: [],
      missing_players: [],
    },
    away: {
      starting_lineups: [],
      substitutes: [],
      coach: [],
      missing_players: [],
    },
  },
  statistics: [],
},
{
  match_id: '230378',
  country_id: '71',
  country_name: 'Japan',
  league_id: '277',
  league_name: 'Emperors Cup',
  match_date: '2019-07-03',
  match_status: 'Finished',
  match_time: '12:00',
  match_hometeam_id: '4370',
  match_hometeam_name: 'Urawa',
  match_hometeam_score: '2',
  match_awayteam_name: 'Ryutsu Keizai University',
  match_awayteam_id: '11009',
  match_awayteam_score: '1',
  match_hometeam_halftime_score: '1',
  match_awayteam_halftime_score: '1',
  match_hometeam_extra_score: '1',
  match_awayteam_extra_score: '1',
  match_hometeam_penalty_score: '',
  match_awayteam_penalty_score: '',
  match_hometeam_system: '',
  match_awayteam_system: '',
  match_live: '0',
  goalscorer: [
    {
      time: '2',
      home_scorer: 'Suzuki D.',
      score: '1 - 0',
      away_scorer: '',
    },
    {
      time: '19',
      home_scorer: '',
      score: '1 - 1',
      away_scorer: 'Taiichi K.',
    },
    {
      time: '74',
      home_scorer: 'Ewerton',
      score: '2 - 1',
      away_scorer: '',
    },
  ],
  cards: [],
  substitutions: {
    home: [],
    away: [],
  },
  lineup: {
    home: {
      starting_lineups: [],
      substitutes: [],
      coach: [],
      missing_players: [],
    },
    away: {
      starting_lineups: [],
      substitutes: [],
      coach: [],
      missing_players: [],
    },
  },
  statistics: [],
},
];
